# Drive and utilities

In [2]:
#@title Mount Drive to get BERT model
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [ ]:
#@title Utils
!pip install dill
!pip install pandas
!pip install numpy
!
import dill as pickle

In [ ]:
#@title Clone the repo and add API key
!git clone https://github.com/amusali/bert_for_patents.git
import os
# Api key setting
os.environ['patentsview_api_key'] = 'Uch9R1RR.BxaQcxV8HK4nBMgTTjX1F9CQW8PF4nXw'  # Replace with your actual key

In [ ]:
#@title Run setup file to get environment
#!python "/content/bert_for_patents/05 Analysis/01 Main/setup_colab.py"

import sys
sys.path.append('/content/bert_for_patents/05 Analysis/01 Main')
os.chdir("/content/bert_for_patents/05 Analysis/01 Main")

In [ ]:
#@title Pull latest changes from repo
%cd "/content/bert_for_patents"
!git pull origin master
#@title Add paths to the system and change directory
import sys
sys.path.append('/content/bert_for_patents/05 Analysis/01 Main')
os.chdir("/content/bert_for_patents/05 Analysis/01 Main")

# Calculate weighted before SMDs

In [ ]:
#@title Functions

import os, glob
import dill as pickle
import numpy as np
import pandas as pd

# ---------- 1) Point this to where you saved precomputed outputs ----------
# Example: "/content/drive/MyDrive/project/precomputed/*.pkl"

paths = sorted(glob.glob(PRECOMPUTED_GLOB, recursive=True))
print(f"Found {len(paths)} precomputed files")
for p in paths[:5]:
    print(" ", p)


# ---------- 2) Utilities ----------
def load_precomputed(path):
    """Load one precomputed object (list of dicts) saved with pickle.
    If you used dill, swap pickle for dill."""
    with open(path, "rb") as f:
        obj = pickle.load(f)
    return obj

def weighted_mean_and_var_from_sums(sum_w, sum_x, sum_x2):
    """Given weight sum and weighted sums of x and x^2, return mean and var."""
    mean = sum_x / sum_w
    var = (sum_x2 / sum_w) - mean**2
    # numerical floor
    var = np.maximum(var, 0.0)
    return mean, var

def compute_before_smds_from_precomputed(precomputed_list, last_k_quarters=4):
    """
    Compute BEFORE-matching SMDs for the last_k_quarters (default 4) closest to treatment:
      relative quarters: t-4, t-3, t-2, t-1

    precomputed_list: output of precompute_mahalanobis (list of dicts).
      Each dict contains:
        - 'treated_vectors': (n_t, Q)
        - 'candidate_vectors': (n_c, Q)
        - 'pre_quarters': list length Q (oldest -> most recent)
    """
    # We will aggregate across all risk sets with the "each treated contributes equally" weighting:
    # Treated: weight 1 per treated observation
    # Controls: within each treated risk set, each control gets weight 1/n_c, so total control weight per treated is 1.
    treated_w = 0.0
    control_w = 0.0

    treated_sum = None
    treated_sum2 = None
    control_sum = None
    control_sum2 = None

    used = 0
    skipped = 0

    for item in precomputed_list:
        T = np.asarray(item.get("treated_vectors"))
        C = np.asarray(item.get("candidate_vectors"))

        if T.ndim != 2 or C.ndim != 2:
            skipped += 1
            continue
        n_t, qT = T.shape
        n_c, qC = C.shape
        if n_t == 0 or n_c == 0 or qT != qC:
            skipped += 1
            continue

        Q = qT
        if last_k_quarters > Q:
            skipped += 1
            continue

        # slice to the last k quarters (closest to treatment)
        T4 = T[:, -last_k_quarters:]
        C4 = C[:, -last_k_quarters:]

        # initialize accumulators
        if treated_sum is None:
            treated_sum  = np.zeros(last_k_quarters, dtype=np.float64)
            treated_sum2 = np.zeros(last_k_quarters, dtype=np.float64)
            control_sum  = np.zeros(last_k_quarters, dtype=np.float64)
            control_sum2 = np.zeros(last_k_quarters, dtype=np.float64)

        # ---- Treated aggregation (unweighted per observation) ----
        treated_w   += n_t
        treated_sum += T4.sum(axis=0)
        treated_sum2 += (T4**2).sum(axis=0)

        # ---- Control aggregation with risk-set weighting ----
        # For each treated obs, controls have weights 1/n_c, so total weight per treated = 1.
        # Thus total control weight contributed by this item = n_t.
        control_w += n_t

        # For one treated obs, weighted mean over controls is mean(C4), and weighted E[X^2] is mean(C4^2)
        c_mean = C4.mean(axis=0)
        c_mean2 = (C4**2).mean(axis=0)

        control_sum  += n_t * c_mean
        control_sum2 += n_t * c_mean2

        used += 1

    if treated_sum is None:
        raise ValueError("No valid groups found in precomputed_list. Check your saved outputs.")

    mean_t, var_t = weighted_mean_and_var_from_sums(treated_w, treated_sum, treated_sum2)
    mean_c, var_c = weighted_mean_and_var_from_sums(control_w, control_sum, control_sum2)

    pooled_sd = np.sqrt((var_t + var_c) / 2.0)
    # avoid division by zero
    pooled_sd = np.where(pooled_sd == 0, np.nan, pooled_sd)

    smd = (mean_t - mean_c) / pooled_sd

    rel_q = [f"t-{last_k_quarters-i}" for i in range(last_k_quarters)]  # e.g., t-4, t-3, t-2, t-1

    out = pd.DataFrame({
        "rel_quarter": rel_q,
        "treated_mean": mean_t,
        "control_mean": mean_c,
        "treated_var": var_t,
        "control_var": var_c,
        "pooled_sd": pooled_sd,
        "SMD": smd,
        "abs_SMD": np.abs(smd),
    })

    meta = {
        "groups_used": used,
        "groups_skipped": skipped,
        "treated_weight_sum": treated_w,
        "control_weight_sum": control_w,
    }
    return out, meta

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Found 12 precomputed files
  /content/drive/MyDrive/uc3m PhD/PhD Data/11 Matches/actual results/citation_no_exact_match_on_grantyear/_aux/precomputed_mahalanobis_M&A_bl_4q.pkl
  /content/drive/MyDrive/uc3m PhD/PhD Data/11 Matches/actual results/citation_no_exact_match_on_grantyear/_aux/precomputed_mahalanobis_M&A_bl_6q.pkl
  /content/drive/MyDrive/uc3m PhD/PhD Data/11 Matches/actual results/citation_no_exact_match_on_grantyear/_aux/precomputed_mahalanobis_M&A_bl_8q.pkl
  /content/drive/MyDrive/uc3m PhD/PhD Data/11 Matches/actual results/citation_no_exact_match_on_grantyear/_aux/precomputed_mahalanobis_M&A_top_tech_80_4q.pkl
  /content/drive/MyDrive/uc3m PhD/PhD Data/11 Matches/actual results/citation_no_exact_match_on_grantyear/_aux/precomputed_mahalanobis_M&A_top_tech_80_6q.pkl

In [ ]:
#@title Calculate
all_tables = []
all_meta = []
from tqdm import tqdm

for path in tqdm(paths, total=len(paths), desc="Going over precomputes"):
    precomputed = load_precomputed(path)  # should be a list of dicts
    print("Loaded the file")
    table, meta = compute_before_smds_from_precomputed(precomputed, last_k_quarters=4)
    table.insert(0, "source_file", os.path.basename(path))
    all_tables.append(table)
    all_meta.append({"source_file": os.path.basename(path), **meta})

before_smds_df = pd.concat(all_tables, ignore_index=True)
meta_df = pd.DataFrame(all_meta)

print("Per-file SMDs (first rows):")
display(before_smds_df)

print("Meta diagnostics:")
display(meta_df)

Going over precomputes:   0%|          | 0/12 [00:00<?, ?it/s]

Loaded the file

Going over precomputes:   8%|▊         | 1/12 [01:21<14:56, 81.50s/it]

Loaded the file

Going over precomputes:  17%|█▋        | 2/12 [02:46<13:55, 83.56s/it]

Loaded the file

Going over precomputes:  25%|██▌       | 3/12 [04:08<12:23, 82.65s/it]

Loaded the file

Going over precomputes:  33%|███▎      | 4/12 [04:38<08:15, 61.99s/it]

Loaded the file

Going over precomputes:  42%|████▏     | 5/12 [05:02<05:38, 48.43s/it]

Loaded the file

Going over precomputes:  50%|█████     | 6/12 [05:31<04:10, 41.77s/it]

Loaded the file

Going over precomputes:  58%|█████▊    | 7/12 [06:38<04:10, 50.14s/it]

Loaded the file

Going over precomputes:  67%|██████▋   | 8/12 [07:48<03:45, 56.32s/it]

Loaded the file

Going over precomputes:  75%|███████▌  | 9/12 [08:47<02:51, 57.21s/it]

Loaded the file

Going over precomputes:  83%|████████▎ | 10/12 [09:11<01:33, 46.79s/it]

Loaded the file

Going over precomputes:  92%|█████████▏| 11/12 [09:29<00:37, 37.93s/it]

Loaded the file

Going over precomputes: 100%|██████████| 12/12 [09:48<00:00, 49.02s/it]

Per-file SMDs (first rows):

,source_file,rel_quarter,treated_mean,control_mean,treated_var,control_var,pooled_sd,SMD,abs_SMD
0,precomputed_mahalanobis_M&A_bl_4q.pkl,t-4,0.518160,0.306080,2.251144,1.772381,1.418366,0.149524,0.149524
1,precomputed_mahalanobis_M&A_bl_4q.pkl,t-3,0.541215,0.339206,3.420214,3.050589,1.798722,0.112307,0.112307
2,precomputed_mahalanobis_M&A_bl_4q.pkl,t-2,0.528898,0.326114,2.597623,2.105469,1.533475,0.132238,0.132238
3,precomputed_mahalanobis_M&A_bl_4q.pkl,t-1,0.480893,0.300985,2.467974,2.038165,1.501023,0.119857,0.119857
4,precomputed_mahalanobis_M&A_bl_6q.pkl,t-4,0.525424,0.311938,2.304743,1.809351,1.434241,0.148849,0.148849
5,precomputed_mahalanobis_M&A_bl_6q.pkl,t-3,0.549906,0.345223,3.520358,3.052346,1.812830,0.112908,0.112908
6,precomputed_mahalanobis_M&A_bl_6q.pkl,t-2,0.531184,0.332360,2.611274,2.125491,1.538955,0.129194,0.129194
7,precomputed_mahalanobis_M&A_bl_6q.pkl,t-1,0.486983,0.305698,2.542287,2.054412,1.516031,0.119579,0.119579
8,precomputed_mahalanobis_M&A_bl_8q.pkl,t-4,0.531123,0.318159,2.316280,1.845690,1.442562,0.147629,0.147629
9,precomputed_mahalanobis_M&A_bl_8q.pkl,t-3,0.552065,0.351530,3.570617,3.118823,1.828858,0.109651,0.109651
10,precomputed_mahalanobis_M&A_bl_8q.pkl,t-2,0.528679,0.337575,2.543302,2.143695,1.530849,0.124836,0.124836
11,precomputed_mahalanobis_M&A_bl_8q.pkl,t-1,0.489703,0.310654,2.514932,2.084966,1.516558,0.118063,0.118063
12,precomputed_mahalanobis_M&A_top_tech_80_4q.pkl,t-4,1.723502,0.369938,6.054117,2.522713,2.070849,0.653628,0.653628
13,precomputed_mahalanobis_M&A_top_tech_80_4q.pkl,t-3,1.794931,0.423600,10.143815,5.187933,2.768731,0.495292,0.495292
14,precomputed_mahalanobis_M&A_top_tech_80_4q.pkl,t-2,1.781106,0.401616,7.175588,3.168259,2.274186,0.606586,0.606586
15,precomputed_mahalanobis_M&A_top_tech_80_4q.pkl,t-1,1.628264,0.379292,7.069186,3.230309,2.269306,0.550376,0.550376
16,precomputed_mahalanobis_M&A_top_tech_80_6q.pkl,t-4,2.101558,0.383514,7.559272,2.725283,2.267659,0.757629,0.757629
17,precomputed_mahalanobis_M&A_top_tech_80_6q.pkl,t-3,2.200430,0.438157,13.135003,5.486206,3.051328,0.577543,0.577543
18,precomputed_mahalanobis_M&A_top_tech_80_6q.pkl,t-2,2.169264,0.415322,8.832715,3.337893,2.466841,0.711007,0.711007
19,precomputed_mahalanobis_M&A_top_tech_80_6q.pkl,t-1,2.008060,0.392083,9.013906,3.426556,2.494039,0.647936,0.647936
20,precomputed_mahalanobis_M&A_top_tech_80_8q.pkl,t-4,1.957216,0.383315,7.181159,2.672617,2.219659,0.709073,0.709073
21,precomputed_mahalanobis_M&A_top_tech_80_8q.pkl,t-3,2.032474,0.436194,12.504616,5.386869,2.990943,0.533704,0.533704
22,precomputed_mahalanobis_M&A_top_tech_80_8q.pkl,t-2,1.985052,0.412567,8.114725,3.286346,2.387579,0.658610,0.658610
23,precomputed_mahalanobis_M&A_top_tech_80_8q.pkl,t-1,1.859278,0.388556,8.360094,3.350497,2.419772,0.607794,0.607794
24,precomputed_mahalanobis_Off deal_bl_4q.pkl,t-4,0.301859,0.314430,1.296471,1.822100,1.248714,-0.010067,0.010067
25,precomputed_mahalanobis_Off deal_bl_4q.pkl,t-3,0.320144,0.310197,1.538995,1.665514,1.265802,0.007858,0.007858
26,precomputed_mahalanobis_Off deal_bl_4q.pkl,t-2,0.372452,0.325930,5.459751,2.180719,1.954542,0.023802,0.023802
27,precomputed_mahalanobis_Off deal_bl_4q.pkl,t-1,0.324041,0.304889,1.186364,1.572542,1.174501,0.016306,0.016306
28,precomputed_mahalanobis_Off deal_bl_6q.pkl,t-4,0.309332,0.321783,1.349916,1.839199,1.262758,-0.009860,0.009860
29,precomputed_mahalanobis_Off deal_bl_6q.pkl,t-3,0.325754,0.316991,1.589289,1.686437,1.279790,0.006848,0.006848
30,precomputed_mahalanobis_Off deal_bl_6q.pkl,t-2,0.381810,0.332692,5.721583,2.234100,1.994453,0.024627,0.024627
31,precomputed_mahalanobis_Off deal_bl_6q.pkl,t-1,0.328123,0.311004,1.221879,1.610225,1.189980,0.014386,0.014386
32,precomputed_mahalanobis_Off deal_bl_8q.pkl,t-4,0.318751,0.328569,1.405995,1.853618,1.276639,-0.007690,0.007690
33,precomputed_mahalanobis_Off deal_bl_8q.pkl,t-3,0.333779,0.322875,1.660340,1.711409,1.298412,0.008397,0.008397
34,precomputed_mahalanobis_Off deal_bl_8q.pkl,t-2,0.391885,0.338915,6.021914,2.293577,2.039055,0.025978,0.025978
35,precomputed_mahalanobis_Off deal_bl_8q.pkl,t-1,0.327267,0.317125,1.168903,1.653563,1.187953,0.008537,0.008537
36,precomputed_mahalanobis_Off deal_top_tech_80_4...,t-4,0.797308,0.343336,3.029383,1.833315,1.559278,0.291142,0.291142
37,precomputed_mahalanobis_Off deal_top_tech_80_4...,t-3,0.845606,0.349136,3.620660,1.824135,1.649969,0.300897,0.300897
38,precomputed_mahalanobis_Off deal_top_tech_80_4...,t-2,0.983769,0.364489,13.819610,2.516916,2.858017,0.216682,0.216682
39,precomputed_mahalanobis_Off deal_top_tech_80_4...,t-1,0.855899,0.340455,2.678364,1.689218,1.477765,0.348799,0.348799
40,precomputed_mahalanobis_Off deal_top_tech_80_6...,t-4,1.060624,0.369845,4.255028,1.934173,1.759148,0.392678,0.392678
41,precomputed_mahalanobis_Off deal_top_tech_80_6...,t-3,1.108043,0.378542,5.086766,1.970665,1.878488,0.388345,0.388345
42,precomputed_mahalanobis_Off deal_top_tech_80_6...,t-2,1.336134,0.395161,20.403220,2.807396,3.406656,0.276216,0.276216
43,precomputed_mahalanobis_Off deal_top_tech_80_6...,t-1,1.115246,0.368495,3.678195,1.835230,1.660335,0.449759,0.449759
44,precomputed_mahalanobis_Off deal_top_tech_80_8...,t-4,0.893414,0.366736,3.674914,1.929513,1.673981,0.314626,0.314626
45,precomputed_mahalanobis_Off deal_top_tech_80_8...,t-3,0.931624,0.371681,4.393515,1.926349,1.777620,0.314996,0.314996
46,precomputed_mahalanobis_Off deal_top_tech_80_8...,t-2,1.111111,0.389008,17.291325,2.765305,3.166751,0.228027,0.228027
47,precomputed_mahalanobis_Off deal_top_tech_80_8...,t-1,0.909502,0.362749,2.939020,1.823844,1.543189,0.354301,0.354301

Meta diagnostics:

,source_file,groups_used,groups_skipped,treated_weight_sum,control_weight_sum
0,precomputed_mahalanobis_M&A_bl_4q.pkl,504,0,9499.0,9499.0
1,precomputed_mahalanobis_M&A_bl_6q.pkl,466,0,9027.0,9027.0
2,precomputed_mahalanobis_M&A_bl_8q.pkl,439,0,8595.0,8595.0
3,precomputed_mahalanobis_M&A_top_tech_80_4q.pkl,289,0,2604.0,2604.0
4,precomputed_mahalanobis_M&A_top_tech_80_6q.pkl,234,0,1861.0,1861.0
5,precomputed_mahalanobis_M&A_top_tech_80_8q.pkl,228,0,1940.0,1940.0
6,precomputed_mahalanobis_Off deal_bl_4q.pkl,305,0,6672.0,6672.0
7,precomputed_mahalanobis_Off deal_bl_6q.pkl,301,0,6333.0,6333.0
8,precomputed_mahalanobis_Off deal_bl_8q.pkl,296,0,5989.0,5989.0
9,precomputed_mahalanobis_Off deal_top_tech_80_4...,206,0,2526.0,2526.0
10,precomputed_mahalanobis_Off deal_top_tech_80_6...,162,0,1666.0,1666.0
11,precomputed_mahalanobis_Off deal_top_tech_80_8...,175,0,1989.0,1989.0

In [ ]:
#@title Save
# Save files
before_smds_df.to_excel(r"/content/drive/MyDrive/uc3m PhD/05 Analysis/01 Main/01 Stata/01 Main/04 Matching quality/out/00 Before SMDs - weeighted.xlsx")

# Calculate unweighted - stacked - before SMDs

In [ ]:
#@title Functions
import numpy as np
import pandas as pd

def compute_simple_before_smd(precomputed_list, last_k_quarters=4):

    treated_all = []
    control_all = []

    for item in precomputed_list:

        T = np.asarray(item.get("treated_vectors"))
        C = np.asarray(item.get("candidate_vectors"))

        if T.ndim != 2 or C.ndim != 2:
            continue

        if T.shape[1] < last_k_quarters:
            continue

        # take last k quarters (closest to treatment)
        treated_all.append(T[:, -last_k_quarters:])
        control_all.append(C[:, -last_k_quarters:])

    if not treated_all:
        raise ValueError("No valid groups found.")

    T_stack = np.vstack(treated_all)
    C_stack = np.vstack(control_all)

    results = []

    for q in range(last_k_quarters):

        treated_q = T_stack[:, q]
        control_q = C_stack[:, q]

        mean_t = treated_q.mean()
        mean_c = control_q.mean()

        sd_t = treated_q.std(ddof=1)
        sd_c = control_q.std(ddof=1)

        pooled_sd = np.sqrt((sd_t**2 + sd_c**2) / 2)

        smd = (mean_t - mean_c) / pooled_sd

        results.append({
            "quarter": f"t-{last_k_quarters-q}",
            "treated_mean": mean_t,
            "treated_sd": sd_t,
            "control_mean": mean_c,
            "control_sd": sd_c,
            "pooled_sd": pooled_sd,
            "SMD": smd,
            "abs_SMD": abs(smd)
        })

    return pd.DataFrame(results)

In [ ]:
#@title Calculate
all_tables_un = []
from tqdm import tqdm

for path in tqdm(paths, total=len(paths), desc="Going over precomputes"):
    precomputed = load_precomputed(path)  # should be a list of dicts
    print("Loaded the file")
    table = compute_simple_before_smd(precomputed, last_k_quarters=4)
    table.insert(0, "source_file", os.path.basename(path))
    all_tables_un.append(table)

before_smds_df_unweighted = pd.concat(all_tables_un, ignore_index=True)

print("Per-file SMDs (first rows):")
display(before_smds_df_unweighted)

Going over precomputes:   0%|          | 0/12 [00:00<?, ?it/s]

Loaded the file

Going over precomputes:   8%|▊         | 1/12 [01:28<16:10, 88.21s/it]

Loaded the file

Going over precomputes:  17%|█▋        | 2/12 [02:53<14:22, 86.26s/it]

Loaded the file

Going over precomputes:  25%|██▌       | 3/12 [04:15<12:41, 84.63s/it]

Loaded the file

Going over precomputes:  33%|███▎      | 4/12 [04:55<08:56, 67.09s/it]

Loaded the file

Going over precomputes:  42%|████▏     | 5/12 [05:26<06:18, 54.02s/it]

Loaded the file

Going over precomputes:  50%|█████     | 6/12 [06:00<04:43, 47.20s/it]

Loaded the file

Going over precomputes:  58%|█████▊    | 7/12 [06:59<04:15, 51.07s/it]

Loaded the file

Going over precomputes:  67%|██████▋   | 8/12 [08:10<03:49, 57.30s/it]

Loaded the file

Going over precomputes:  75%|███████▌  | 9/12 [09:27<03:10, 63.49s/it]

Loaded the file

Going over precomputes:  83%|████████▎ | 10/12 [09:58<01:46, 53.40s/it]

Loaded the file

Going over precomputes:  92%|█████████▏| 11/12 [10:20<00:43, 43.68s/it]

Loaded the file

Going over precomputes: 100%|██████████| 12/12 [10:41<00:00, 53.50s/it]

Per-file SMDs (first rows):

,source_file,quarter,treated_mean,treated_sd,control_mean,control_sd,pooled_sd,SMD,abs_SMD
0,precomputed_mahalanobis_M&A_bl_4q.pkl,t-4,0.518160,1.500460,0.301121,1.733219,1.621023,0.133890,0.133890
1,precomputed_mahalanobis_M&A_bl_4q.pkl,t-3,0.541215,1.849479,0.295333,1.645912,1.750657,0.140451,0.140451
2,precomputed_mahalanobis_M&A_bl_4q.pkl,t-2,0.528898,1.611799,0.296582,1.736611,1.675368,0.138666,0.138666
3,precomputed_mahalanobis_M&A_bl_4q.pkl,t-1,0.480893,1.571061,0.282669,1.528380,1.549868,0.127898,0.127898
4,precomputed_mahalanobis_M&A_bl_6q.pkl,t-4,0.525424,1.518222,0.300400,1.769565,1.648690,0.136486,0.136486
5,precomputed_mahalanobis_M&A_bl_6q.pkl,t-3,0.549906,1.876366,0.290677,1.641197,1.762708,0.147063,0.147063
6,precomputed_mahalanobis_M&A_bl_6q.pkl,t-2,0.531184,1.616033,0.292096,1.752568,1.685683,0.141835,0.141835
7,precomputed_mahalanobis_M&A_bl_6q.pkl,t-1,0.486983,1.594543,0.277766,1.540345,1.567678,0.133457,0.133457
8,precomputed_mahalanobis_M&A_bl_8q.pkl,t-4,0.531123,1.522021,0.303036,1.794464,1.663829,0.137086,0.137086
9,precomputed_mahalanobis_M&A_bl_8q.pkl,t-3,0.552065,1.889717,0.292601,1.668510,1.782548,0.145558,0.145558
10,precomputed_mahalanobis_M&A_bl_8q.pkl,t-2,0.528679,1.594866,0.293271,1.783743,1.691942,0.139135,0.139135
11,precomputed_mahalanobis_M&A_bl_8q.pkl,t-1,0.489703,1.585946,0.277497,1.555996,1.571043,0.135074,0.135074
12,precomputed_mahalanobis_M&A_top_tech_80_4q.pkl,t-4,1.723502,2.460984,0.331962,1.930088,2.211525,0.629222,0.629222
13,precomputed_mahalanobis_M&A_top_tech_80_4q.pkl,t-3,1.794931,3.185547,0.325356,1.804857,2.588940,0.567636,0.567636
14,precomputed_mahalanobis_M&A_top_tech_80_4q.pkl,t-2,1.781106,2.679243,0.328635,1.935368,2.337092,0.621487,0.621487
15,precomputed_mahalanobis_M&A_top_tech_80_4q.pkl,t-1,1.628264,2.659305,0.311250,1.665425,2.218732,0.593589,0.593589
16,precomputed_mahalanobis_M&A_top_tech_80_6q.pkl,t-4,2.101558,2.750152,0.338465,2.043098,2.422559,0.727781,0.727781
17,precomputed_mahalanobis_M&A_top_tech_80_6q.pkl,t-3,2.200430,3.625199,0.326130,1.826892,2.870505,0.652951,0.652951
18,precomputed_mahalanobis_M&A_top_tech_80_6q.pkl,t-2,2.169264,2.972787,0.323445,1.852946,2.476981,0.745189,0.745189
19,precomputed_mahalanobis_M&A_top_tech_80_6q.pkl,t-1,2.008060,3.003124,0.309116,1.670527,2.429960,0.699165,0.699165
20,precomputed_mahalanobis_M&A_top_tech_80_8q.pkl,t-4,1.957216,2.680459,0.349348,2.090509,2.403652,0.668927,0.668927
21,precomputed_mahalanobis_M&A_top_tech_80_8q.pkl,t-3,2.032474,3.537098,0.337937,1.931053,2.849564,0.594665,0.594665
22,precomputed_mahalanobis_M&A_top_tech_80_8q.pkl,t-2,1.985052,2.849370,0.340996,2.088705,2.498159,0.658107,0.658107
23,precomputed_mahalanobis_M&A_top_tech_80_8q.pkl,t-1,1.859278,2.892128,0.319054,1.752389,2.391158,0.644133,0.644133
24,precomputed_mahalanobis_Off deal_bl_4q.pkl,t-4,0.301859,1.138712,0.299685,1.275944,1.209276,0.001798,0.001798
25,precomputed_mahalanobis_Off deal_bl_4q.pkl,t-3,0.320144,1.240655,0.304539,1.261404,1.251073,0.012473,0.012473
26,precomputed_mahalanobis_Off deal_bl_4q.pkl,t-2,0.372452,2.336786,0.315450,1.482261,1.956741,0.029131,0.029131
27,precomputed_mahalanobis_Off deal_bl_4q.pkl,t-1,0.324041,1.089285,0.306553,1.284443,1.190869,0.014685,0.014685
28,precomputed_mahalanobis_Off deal_bl_6q.pkl,t-4,0.309332,1.161951,0.305066,1.290687,1.228007,0.003474,0.003474
29,precomputed_mahalanobis_Off deal_bl_6q.pkl,t-3,0.325754,1.260770,0.309891,1.276079,1.268448,0.012506,0.012506
30,precomputed_mahalanobis_Off deal_bl_6q.pkl,t-2,0.381810,2.392172,0.320581,1.501357,1.997068,0.030659,0.030659
31,precomputed_mahalanobis_Off deal_bl_6q.pkl,t-1,0.328123,1.105474,0.309271,1.288187,1.200312,0.015706,0.015706
32,precomputed_mahalanobis_Off deal_bl_8q.pkl,t-4,0.318751,1.185846,0.309230,1.300987,1.244748,0.007649,0.007649
33,precomputed_mahalanobis_Off deal_bl_8q.pkl,t-3,0.333779,1.288649,0.313742,1.287256,1.287953,0.015557,0.015557
34,precomputed_mahalanobis_Off deal_bl_8q.pkl,t-2,0.391885,2.454164,0.324256,1.518688,2.040751,0.033140,0.033140
35,precomputed_mahalanobis_Off deal_bl_8q.pkl,t-1,0.327267,1.081248,0.312362,1.299605,1.195423,0.012468,0.012468
36,precomputed_mahalanobis_Off deal_top_tech_80_4...,t-4,0.797308,1.740857,0.320628,1.322122,1.545734,0.308384,0.308384
37,precomputed_mahalanobis_Off deal_top_tech_80_4...,t-3,0.845606,1.903180,0.330193,1.337587,1.644876,0.313344,0.313344
38,precomputed_mahalanobis_Off deal_top_tech_80_4...,t-2,0.983769,3.718210,0.341270,1.565870,2.852808,0.225216,0.225216
39,precomputed_mahalanobis_Off deal_top_tech_80_4...,t-1,0.855899,1.636895,0.330701,1.345649,1.498365,0.350514,0.350514
40,precomputed_mahalanobis_Off deal_top_tech_80_6...,t-4,1.060624,2.063391,0.335201,1.372436,1.752308,0.413981,0.413981
41,precomputed_mahalanobis_Off deal_top_tech_80_6...,t-3,1.108043,2.256063,0.344201,1.381579,1.870639,0.408332,0.408332
42,precomputed_mahalanobis_Off deal_top_tech_80_6...,t-2,1.336134,4.518349,0.356852,1.634619,3.397606,0.288227,0.288227
43,precomputed_mahalanobis_Off deal_top_tech_80_6...,t-1,1.115246,1.918438,0.342176,1.381325,1.671595,0.462475,0.462475
44,precomputed_mahalanobis_Off deal_top_tech_80_8...,t-4,0.893414,1.917489,0.336306,1.368089,1.665597,0.334479,0.334479
45,precomputed_mahalanobis_Off deal_top_tech_80_8...,t-3,0.931624,2.096598,0.344499,1.375598,1.773132,0.331123,0.331123
46,precomputed_mahalanobis_Off deal_top_tech_80_8...,t-2,1.111111,4.159330,0.356251,1.628678,3.158529,0.238991,0.238991
47,precomputed_mahalanobis_Off deal_top_tech_80_8...,t-1,0.909502,1.714788,0.341908,1.377187,1.555176,0.364972,0.364972

In [ ]:
#@title Save
# Save files
before_smds_df_unweighted.to_excel(r"/content/drive/MyDrive/uc3m PhD/05 Analysis/01 Main/01 Stata/01 Main/04 Matching quality/out/00 Before SMDs - unweighted.xlsx")

# Before SMDs of PCAs

In [ ]:
# import a csv
t = pd.read_csv(r"/content/drive/MyDrive/uc3m PhD/PhD Data/01 CLS Embeddings/All embeddings - float16/PCA/pca_3D.csv")

/tmp/ipython-input-1154216605.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  t = pd.read_csv(r"/content/drive/MyDrive/uc3m PhD/PhD Data/01 CLS Embeddings/All embeddings - float16/PCA/pca_3D.csv")

In [ ]:
t.dtypes

patent_id     object
PC1          float64
PC2          float64
PC3          float64
dtype: object

In [ ]:
#@title Functions
import os, glob
import dill as pickle
import numpy as np
import pandas as pd
PRECOMPUTED_GLOB = r"/content/drive/MyDrive/uc3m PhD/PhD Data/11 Matches/actual results/citation_no_exact_match_on_grantyear/_aux/precomputed*.pkl"

paths = sorted(glob.glob(PRECOMPUTED_GLOB, recursive=True))
print(f"Found {len(paths)} precomputed files")
PCA_CSV_PATH = r"/content/drive/MyDrive/uc3m PhD/PhD Data/01 CLS Embeddings/All embeddings - float16/PCA/pca_10D.csv"
N_PCS = 10

OUT_DIR = "/content/drive/MyDrive/uc3m PhD/05 Analysis/01 Main/01 Stata/01 Main/04 Matching quality/out"

# ----------------------------
# 1) Loaders
# ----------------------------

def load_precomputed(path):
    """Load one precomputed object (list of dicts) saved with pickle.
    If you used dill, swap pickle for dill."""
    with open(path, "rb") as f:
        obj = pickle.load(f)
    return obj


def load_pca_csv(path: str, n_pcs: int = 10) -> pd.DataFrame:
    # Force patent_id to string to avoid mixed-type warnings
    df = pd.read_csv(path, dtype={"patent_id": "string"}, low_memory=False)

    required = ["patent_id"] + [f"PC{i}" for i in range(1, n_pcs + 1)]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(
            f"PCA file missing columns: {missing}\n"
            f"Found columns (first 40): {df.columns.tolist()[:40]}"
        )

    for i in range(1, n_pcs + 1):
        df[f"PC{i}"] = pd.to_numeric(df[f"PC{i}"], errors="coerce")

    df = df.dropna(subset=["patent_id"])
    df["patent_id"] = df["patent_id"].astype("string")

    # Keep only required columns
    return df[required]


# ----------------------------
# 2) Extract UNIQUE treated ids and UNIQUE candidate ids
# ----------------------------
def extract_unique_ids(precomputed_list):
    treated_ids = set()
    candidate_ids = set()

    for item in precomputed_list:
        tids = item.get("treated_ids", [])
        cids = item.get("candidate_ids", [])

        # normalize to string
        for t in tids:
            treated_ids.add(str(t))
        for c in cids:
            candidate_ids.add(str(c))

    return treated_ids, candidate_ids


# ----------------------------
# 3) SMD computation (unweighted, two unique samples)
# ----------------------------
def smd_table_unweighted(treated_df: pd.DataFrame, control_df: pd.DataFrame, covariates):
    rows = []
    for var in covariates:
        xt = treated_df[var].to_numpy(dtype=np.float64)
        xc = control_df[var].to_numpy(dtype=np.float64)

        # drop NaN (just in case)
        xt = xt[np.isfinite(xt)]
        xc = xc[np.isfinite(xc)]

        mean_t = xt.mean()
        mean_c = xc.mean()
        sd_t = xt.std(ddof=1)
        sd_c = xc.std(ddof=1)
        pooled_sd = np.sqrt((sd_t**2 + sd_c**2) / 2.0)
        smd = (mean_t - mean_c) / pooled_sd if pooled_sd != 0 else np.nan

        rows.append({
            "covariate": var,
            "treated_mean": mean_t,
            "treated_sd": sd_t,
            "control_mean": mean_c,
            "control_sd": sd_c,
            "pooled_sd": pooled_sd,
            "SMD": smd,
            "abs_SMD": abs(smd) if np.isfinite(smd) else np.nan,
            "n_treated": len(xt),
            "n_controls": len(xc),
        })
    return pd.DataFrame(rows)

Found 12 precomputed files

In [ ]:
#@title Calculate
from tqdm import tqdm

# Load PCA
pca = load_pca_csv(PCA_CSV_PATH, n_pcs=N_PCS)
print("PCA loaded:", pca.shape)

# Load all precomputed files
paths = sorted(glob.glob(PRECOMPUTED_GLOB, recursive=True))
if not paths:
    raise FileNotFoundError(f"No precomputed files found with: {PRECOMPUTED_GLOB}")

all_results = []

for p in tqdm(paths, total = len(paths), desc = "Loopoing over paths"):
    precomputed = load_precomputed(p)
    if not isinstance(precomputed, list):
        raise TypeError(f"Expected list in {p}, got {type(precomputed)}")

    # unique IDs *within this file/config only*
    treated_ids, candidate_ids = extract_unique_ids(precomputed)

    print(f"number of controls before: {len(candidate_ids)}")
    # IMPORTANT:
    candidate_ids = candidate_ids - treated_ids  # keep sets disjoint
    print(f"number of controls after: {len(candidate_ids)}")

    treated_pca = pca[pca["patent_id"].isin(treated_ids)].copy()
    control_pca = pca[pca["patent_id"].isin(candidate_ids)].copy()

    pcs = [f"PC{i}" for i in range(1, N_PCS + 1)]
    balance_pcs = smd_table_unweighted(treated_pca, control_pca, pcs)

    # tag results with config/file name
    balance_pcs.insert(0, "config_file", os.path.basename(p))
    balance_pcs.insert(1, "n_unique_treated_ids", len(treated_ids))
    balance_pcs.insert(2, "n_unique_candidate_ids", len(candidate_ids))
    balance_pcs.insert(3, "n_treated_with_pca", len(treated_pca))
    balance_pcs.insert(4, "n_controls_with_pca", len(control_pca))

    all_results.append(balance_pcs)

# --- CHANGE 2: combine results at the very end (no cross-file dedupe/stacking) ---
results_df = pd.concat(all_results, ignore_index=True)

Loopoing over paths:   0%|          | 0/12 [00:00<?, ?it/s]

number of controls before: 4067852
number of controls after: 4067852

Loopoing over paths:   8%|▊         | 1/12 [02:23<26:15, 143.26s/it]

number of controls before: 3925937
number of controls after: 3925937

Loopoing over paths:  17%|█▋        | 2/12 [04:46<23:52, 143.22s/it]

number of controls before: 3762048
number of controls after: 3762048

Loopoing over paths:  25%|██▌       | 3/12 [07:07<21:20, 142.30s/it]

number of controls before: 3245318
number of controls after: 3245318

Loopoing over paths:  33%|███▎      | 4/12 [08:02<14:23, 107.95s/it]

number of controls before: 3038388
number of controls after: 3038388

Loopoing over paths:  42%|████▏     | 5/12 [08:54<10:13, 87.63s/it]

number of controls before: 2919850
number of controls after: 2919850

Loopoing over paths:  50%|█████     | 6/12 [09:36<07:12, 72.02s/it]

number of controls before: 2828034
number of controls after: 2828034

Loopoing over paths:  58%|█████▊    | 7/12 [11:09<06:35, 79.04s/it]

number of controls before: 2741701
number of controls after: 2741701

Loopoing over paths:  67%|██████▋   | 8/12 [12:38<05:28, 82.21s/it]

number of controls before: 2645290
number of controls after: 2645290

Loopoing over paths:  75%|███████▌  | 9/12 [14:15<04:20, 86.69s/it]

number of controls before: 2183970
number of controls after: 2183970

Loopoing over paths:  83%|████████▎ | 10/12 [15:07<02:32, 76.17s/it]

number of controls before: 1884303
number of controls after: 1884303

Loopoing over paths:  92%|█████████▏| 11/12 [15:44<01:04, 64.14s/it]

number of controls before: 1872125
number of controls after: 1872125

Loopoing over paths: 100%|██████████| 12/12 [16:26<00:00, 82.23s/it]

In [ ]:
# --- CHANGE 3: save single output (or one-per-file if you prefer) ---
out_path = os.path.join(OUT_DIR, "00 Before SMDs PCAs.csv")
results_df.to_csv(out_path, index=False)
print("Saved:", out_path)

Saved: /content/drive/MyDrive/uc3m PhD/05 Analysis/01 Main/01 Stata/01 Main/04 Matching quality/out/00 Before SMDs PCAs.csv

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=results_df)

MessageError: Error: credential propagation was unsuccessful

In [3]:
import pandas as pd

pca = pd.read_csv(r"/content/drive/MyDrive/uc3m PhD/PhD Data/01 CLS Embeddings/All embeddings - float16/PCA/pca_10D.csv")

/tmp/ipython-input-1455/3290459783.py:3: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  pca = pd.read_csv(r"/content/drive/MyDrive/uc3m PhD/PhD Data/01 CLS Embeddings/All embeddings - float16/PCA/pca_10D.csv")

In [4]:
pca.head()

,patent_id,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10
0,10000001,0.866372,5.954933,6.394658,-0.551546,4.521981,-0.101108,1.240542,-5.135097,-1.519952,-3.057474
1,10000002,1.121164,6.867592,2.962751,3.998940,-1.723198,-6.093444,-3.118760,1.807858,-3.117344,0.631172
2,10000003,3.121801,3.129339,-2.616843,4.916008,-0.811856,-7.222512,-0.979107,2.071569,-3.873968,-5.267483
3,10000004,0.534734,-0.204596,2.541621,-4.801057,0.431866,-3.266522,-2.002393,2.284087,-7.102862,-0.468413
4,10000005,2.865330,3.024400,0.713367,1.831444,3.363750,-5.766662,1.591319,0.632718,-1.417394,-1.508772

In [12]:
print(pca[pca['patent_id'] == 10078376])

        patent_id       PC1       PC2       PC3       PC4       PC5       PC6  \
7583260  10078376  3.488712  7.801583 -5.674872 -0.011894 -2.200841  0.082953

              PC7       PC8       PC9      PC10
7583260 -0.122243 -1.447685 -1.802509  1.557432

In [ ]:
wr