# Drive and utilities

In [1]:
#@title Mount Drive to get BERT model
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [2]:
#@title Utils
!pip install dill
!pip install pandas
!pip install numpy
!
import dill as pickle

Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [3]:
#@title Clone the repo and add API key
!git clone https://github.com/amusali/bert_for_patents.git
import os
# Api key setting
os.environ['patentsview_api_key'] = 'Uch9R1RR.BxaQcxV8HK4nBMgTTjX1F9CQW8PF4nXw'  # Replace with your actual key

Cloning into 'bert_for_patents'...
remote: Enumerating objects: 1995, done.
remote: Counting objects: 100% (253/253), done.
remote: Compressing objects: 100% (113/113), done.
remote: Total 1995 (delta 156), reused 221 (delta 137), pack-reused 1742 (from 2)
Receiving objects: 100% (1995/1995), 206.70 MiB | 40.55 MiB/s, done.
Resolving deltas: 100% (1115/1115), done.

In [4]:
#@title Run setup file to get environment
#!python "/content/bert_for_patents/05 Analysis/01 Main/setup_colab.py"

import sys
sys.path.append('/content/bert_for_patents/05 Analysis/01 Main')
os.chdir("/content/bert_for_patents/05 Analysis/01 Main")

In [5]:
#@title Pull latest changes from repo
%cd "/content/bert_for_patents"
!git pull origin master
#@title Add paths to the system and change directory
import sys
sys.path.append('/content/bert_for_patents/05 Analysis/01 Main')
os.chdir("/content/bert_for_patents/05 Analysis/01 Main")

/content/bert_for_patents
From https://github.com/amusali/bert_for_patents
 * branch            master     -> FETCH_HEAD
Already up to date.

# Collapse & save citations

In [6]:
# Example: copy MyDrive/data_big to local /content/data_big
!mkdir -p "/content/matches"
!rsync -a --info=progress2 \
  --include='01 Hybrid matches (lambda 0.6 and 0.7) - *10matches.pkl' \
  --exclude='*' \
  "/content/drive/MyDrive/PhD Data/11 Matches/actual results/paper/" \
  "/content/matches/"

    479,867,144 100%   17.21MB/s    0:00:26 (xfr#24, to-chk=0/25)

In [7]:
import api.process_matches_no_exact as processing
import importlib
importlib.reload(processing)
import pandas as pd

## Collapse citations
cits = processing.collapse_citations()

## Save collapsed citations
processing.save_collapsed_citations(cits)
cits.to_csv("/content/drive/MyDrive/PhD Data/12 Sample Final/actual results/paper/collapsed_citations (lam 0.6 and 0.7).csv")

Loading samples: 100%|██████████| 24/24 [00:18<00:00,  1.31it/s]

In [ ]:
# Load the collapsed citation file as pickle and save it as CSV
import pandas as pd

cits = pd.read_pickle("/content/drive/MyDrive/PhD Data/12 Sample Final/actual results/citation_noexactmatch_on_grantyear/collapsed_citations.pkl")
cits.to_csv("/content/drive/MyDrive/PhD Data/12 Sample Final/actual results/citation_noexactmatch_on_grantyear/collapsed_citations.csv")

# Save files into Colab

In [ ]:
# Example: copy MyDrive/data_big to local /content/data_big
!mkdir -p "/content/matches"
!rsync -a --info=progress2 \
  --include='01 Hybrid matches - *10matches.pkl' \
  --exclude='*' \
  "/content/drive/MyDrive/PhD Data/11 Matches/actual results/citation_no_exact_match_on_grantyear/" \
  "/content/matches/"

  1,218,103,335 100%   40.47MB/s    0:00:28 (xfr#24, to-chk=0/25)

# Not run anymore but kept here just in case

In [ ]:
import api.process_matches as processing
import importlib
importlib.reload(processing)
import pandas as pd

citations = processing.load_pickle("/content/drive/MyDrive/PhD Data/12 Sample Final/actual results/citation/collapsed_citations_old.pkl")
citations['citation_quarter'] = pd.PeriodIndex(citations['citation_quarter'], freq='Q')
# Build a MultiIndex once from collapsed citations and keep only the count
collapsed_citations = (
    citations
    .set_index(['patent_id', 'citation_quarter'])['citation_count']
)

#lookup = cc.to_dict()

patents = pd.read_stata("/content/drive/MyDrive/PhD Data/09 Acquired patents/04 All patents.dta")
patents['patent_id'] = patents['patent_id'].astype(str)

patents = patents[['patent_id', 'ult_parent', 'acq_type', 'acq_date', 'deal_id', 'resold_date']]

processing.finalize_all(collapsed_citations, patents)

Processing samples:   0%|          | 0/120 [00:00<?, ?it/s]

Processing 01 Hybrid matches - Off deal, top-tech, 80, 6q, caliper_0.0250, 10matches.pkl
 - Loaded sample in 0.551s
 - Combined with citations in 9.728s
 -> Total process_sample time: 10.624s
 - Merged with patents metadata in 0.876s

Processing samples:   1%|          | 1/120 [00:17<34:42, 17.50s/it]

 - Saved Pickle file in 4.834s
Finalized sample>Off deal, top-tech, 80, 6q, caliper_0.0250, 10matches with 2440581 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 90, 10q, caliper_0.0500, 10matches.pkl
 - Loaded sample in 0.853s
 - Combined with citations in 12.342s
 -> Total process_sample time: 14.540s
 - Merged with patents metadata in 1.665s

Processing samples:   2%|▏         | 2/120 [00:42<43:23, 22.07s/it]

 - Saved Pickle file in 7.405s
Finalized sample>Off deal, top-tech, 90, 10q, caliper_0.0500, 10matches with 3775266 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 80, 12q, caliper_0.0250, 10matches.pkl
 - Loaded sample in 0.439s
 - Combined with citations in 9.813s
 -> Total process_sample time: 10.670s
 - Merged with patents metadata in 1.176s

Processing samples:   2%|▎         | 3/120 [01:09<46:50, 24.02s/it]

 - Saved Pickle file in 13.452s
Finalized sample>Off deal, top-tech, 80, 12q, caliper_0.0250, 10matches with 2989374 rows.

Processing 01 Hybrid matches - M&A, top-tech, 80, 8q, caliper_0.0250, 10matches.pkl
 - Loaded sample in 1.078s
 - Combined with citations in 6.387s
 -> Total process_sample time: 7.691s
 - Merged with patents metadata in 0.574s

Processing samples:   3%|▎         | 4/120 [01:21<37:43, 19.51s/it]

 - Saved Pickle file in 3.891s
Finalized sample>M&A, top-tech, 80, 8q, caliper_0.0250, 10matches with 1557682 rows.

Processing 01 Hybrid matches - M&A, baseline, 4q, caliper_0.1000, 10matches.pkl
 - Loaded sample in 19.251s
 - Combined with citations in 245.368s
 -> Total process_sample time: 291.960s
 - Merged with patents metadata in 22.042s

Processing samples:   4%|▍         | 5/120 [10:04<6:25:31, 201.14s/it]

 - Saved Pickle file in 185.512s
Finalized sample>M&A, baseline, 4q, caliper_0.1000, 10matches with 59067299 rows.

Processing 01 Hybrid matches - M&A, top-tech, 90, 6q, caliper_0.0250, 10matches.pkl
 - Loaded sample in 0.112s
 - Combined with citations in 2.869s
 -> Total process_sample time: 3.093s
 - Merged with patents metadata in 2.774s

Processing samples:   5%|▌         | 6/120 [10:13<4:17:32, 135.55s/it]

 - Saved Pickle file in 1.002s
Finalized sample>M&A, top-tech, 90, 6q, caliper_0.0250, 10matches with 691298 rows.

Processing 01 Hybrid matches - M&A, top-tech, 90, 12q, caliper_0.0500, 10matches.pkl
 - Loaded sample in 0.444s
 - Combined with citations in 8.071s
 -> Total process_sample time: 8.804s
 - Merged with patents metadata in 0.634s

Processing samples:   6%|▌         | 7/120 [14:54<5:44:48, 183.08s/it]

 - Saved Pickle file in 271.113s
Finalized sample>M&A, top-tech, 90, 12q, caliper_0.0500, 10matches with 2045822 rows.

Processing 01 Hybrid matches - Off deal, baseline, 4q, caliper_0.0750, 10matches.pkl
 - Loaded sample in 12.769s
 - Combined with citations in 191.665s
 -> Total process_sample time: 216.491s
 - Merged with patents metadata in 17.158s

Processing samples:   7%|▋         | 8/120 [20:45<7:21:54, 236.74s/it]

 - Saved Pickle file in 102.630s
Finalized sample>Off deal, baseline, 4q, caliper_0.0750, 10matches with 46370570 rows.

Processing 01 Hybrid matches - M&A, top-tech, 80, 6q, caliper_0.0500, 10matches.pkl
 - Loaded sample in 0.506s
 - Combined with citations in 17.061s
 -> Total process_sample time: 18.249s
 - Merged with patents metadata in 3.779s

Processing samples:   8%|▊         | 9/120 [21:17<5:19:18, 172.60s/it]

 - Saved Pickle file in 7.442s
Finalized sample>M&A, top-tech, 80, 6q, caliper_0.0500, 10matches with 4394688 rows.

Processing 01 Hybrid matches - Off deal, baseline, 4q, caliper_0.1000, 10matches.pkl
 - Loaded sample in 13.977s
 - Combined with citations in 187.877s
 -> Total process_sample time: 219.015s
 - Merged with patents metadata in 18.914s

Processing samples:   8%|▊         | 10/120 [26:57<6:51:11, 224.29s/it]

 - Saved Pickle file in 83.555s
Finalized sample>Off deal, baseline, 4q, caliper_0.1000, 10matches with 49802015 rows.

Processing 01 Hybrid matches - M&A, baseline, 8q, caliper_0.0750, 10matches.pkl
 - Loaded sample in 11.098s
 - Combined with citations in 229.349s
 -> Total process_sample time: 259.785s
 - Merged with patents metadata in 20.190s

Processing samples:   9%|▉         | 11/120 [33:21<8:16:36, 273.36s/it]

 - Saved Pickle file in 88.291s
Finalized sample>M&A, baseline, 8q, caliper_0.0750, 10matches with 48453628 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 80, 10q, caliper_0.0500, 10matches.pkl
 - Loaded sample in 1.479s
 - Combined with citations in 26.069s
 -> Total process_sample time: 29.106s
 - Merged with patents metadata in 5.133s

Processing samples:  10%|█         | 12/120 [34:10<6:09:07, 205.07s/it]

 - Saved Pickle file in 11.366s
Finalized sample>Off deal, top-tech, 80, 10q, caliper_0.0500, 10matches with 8039915 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 80, 4q, caliper_0.0250, 10matches.pkl
 - Loaded sample in 1.246s
 - Combined with citations in 21.167s
 -> Total process_sample time: 23.155s
 - Merged with patents metadata in 2.021s

Processing samples:  11%|█         | 13/120 [34:45<4:33:25, 153.32s/it]

 - Saved Pickle file in 7.722s
Finalized sample>Off deal, top-tech, 80, 4q, caliper_0.0250, 10matches with 5594765 rows.

Processing 01 Hybrid matches - Off deal, baseline, 10q, caliper_0.1000, 10matches.pkl
 - Loaded sample in 10.255s
 - Combined with citations in 170.427s
 -> Total process_sample time: 195.994s
 - Merged with patents metadata in 23.800s

Processing samples:  12%|█▏        | 14/120 [39:54<5:54:20, 200.57s/it]

 - Saved Pickle file in 72.651s
Finalized sample>Off deal, baseline, 10q, caliper_0.1000, 10matches with 48548634 rows.

Processing 01 Hybrid matches - M&A, top-tech, 90, 10q, caliper_0.0750, 10matches.pkl
 - Loaded sample in 0.712s
 - Combined with citations in 14.588s
 -> Total process_sample time: 15.846s
 - Merged with patents metadata in 3.522s

Processing samples:  12%|█▎        | 15/120 [40:21<4:19:31, 148.30s/it]

 - Saved Pickle file in 6.089s
Finalized sample>M&A, top-tech, 90, 10q, caliper_0.0750, 10matches with 3862285 rows.

Processing 01 Hybrid matches - M&A, top-tech, 90, 10q, caliper_0.0250, 10matches.pkl
 - Loaded sample in 0.229s
 - Combined with citations in 3.516s
 -> Total process_sample time: 3.852s
 - Merged with patents metadata in 0.360s

Processing samples:  13%|█▎        | 16/120 [40:27<3:02:28, 105.27s/it]

 - Saved Pickle file in 0.953s
Finalized sample>M&A, top-tech, 90, 10q, caliper_0.0250, 10matches with 651706 rows.

Processing 01 Hybrid matches - M&A, top-tech, 80, 10q, caliper_0.0500, 10matches.pkl
 - Loaded sample in 1.335s
 - Combined with citations in 36.165s
 -> Total process_sample time: 38.184s
 - Merged with patents metadata in 1.547s

Processing samples:  14%|█▍        | 17/120 [41:19<2:33:17, 89.30s/it]

 - Saved Pickle file in 11.372s
Finalized sample>M&A, top-tech, 80, 10q, caliper_0.0500, 10matches with 5124063 rows.

Processing 01 Hybrid matches - M&A, top-tech, 80, 8q, caliper_0.1000, 10matches.pkl
 - Loaded sample in 2.560s
 - Combined with citations in 42.892s
 -> Total process_sample time: 48.991s
 - Merged with patents metadata in 4.107s

Processing samples:  15%|█▌        | 18/120 [42:35<2:24:50, 85.21s/it]

 - Saved Pickle file in 19.520s
Finalized sample>M&A, top-tech, 80, 8q, caliper_0.1000, 10matches with 11434120 rows.

Processing 01 Hybrid matches - M&A, baseline, 12q, caliper_0.0500, 10matches.pkl
 - Loaded sample in 7.405s
 - Combined with citations in 122.263s
 -> Total process_sample time: 142.648s
 - Merged with patents metadata in 12.704s

Processing samples:  16%|█▌        | 19/120 [46:15<3:31:42, 125.77s/it]

 - Saved Pickle file in 53.062s
Finalized sample>M&A, baseline, 12q, caliper_0.0500, 10matches with 31778116 rows.

Processing 01 Hybrid matches - M&A, top-tech, 80, 8q, caliper_0.0500, 10matches.pkl
 - Loaded sample in 1.133s
 - Combined with citations in 19.669s
 -> Total process_sample time: 21.892s
 - Merged with patents metadata in 6.251s

Processing samples:  17%|█▋        | 20/120 [46:59<2:48:59, 101.40s/it]

 - Saved Pickle file in 13.432s
Finalized sample>M&A, top-tech, 80, 8q, caliper_0.0500, 10matches with 4867107 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 80, 6q, caliper_0.0750, 10matches.pkl
 - Loaded sample in 2.394s
 - Combined with citations in 43.436s
 -> Total process_sample time: 48.073s
 - Merged with patents metadata in 3.919s

Processing samples:  18%|█▊        | 21/120 [48:10<2:31:47, 92.00s/it]

 - Saved Pickle file in 14.805s
Finalized sample>Off deal, top-tech, 80, 6q, caliper_0.0750, 10matches with 11285380 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 80, 10q, caliper_0.1000, 10matches.pkl
 - Loaded sample in 2.353s
 - Combined with citations in 45.819s
 -> Total process_sample time: 51.196s
 - Merged with patents metadata in 5.271s

Processing samples:  18%|█▊        | 22/120 [49:29<2:23:54, 88.11s/it]

 - Saved Pickle file in 18.364s
Finalized sample>Off deal, top-tech, 80, 10q, caliper_0.1000, 10matches with 13938036 rows.

Processing 01 Hybrid matches - Off deal, baseline, 4q, caliper_0.0250, 10matches.pkl
 - Loaded sample in 6.091s
 - Combined with citations in 97.259s
 -> Total process_sample time: 132.969s
 - Merged with patents metadata in 10.201s

Processing samples:  19%|█▉        | 23/120 [52:40<3:12:35, 119.13s/it]

 - Saved Pickle file in 37.184s
Finalized sample>Off deal, baseline, 4q, caliper_0.0250, 10matches with 23910420 rows.

Processing 01 Hybrid matches - M&A, baseline, 6q, caliper_0.1000, 10matches.pkl
 - Loaded sample in 13.927s
 - Combined with citations in 238.925s
 -> Total process_sample time: 284.277s
 - Merged with patents metadata in 26.299s

Processing samples:  20%|██        | 24/120 [59:56<5:42:37, 214.14s/it]

 - Saved Pickle file in 105.323s
Finalized sample>M&A, baseline, 6q, caliper_0.1000, 10matches with 57893359 rows.

Processing 01 Hybrid matches - M&A, top-tech, 90, 12q, caliper_0.0750, 10matches.pkl
 - Loaded sample in 0.395s
 - Combined with citations in 13.876s
 -> Total process_sample time: 14.810s
 - Merged with patents metadata in 3.897s

Processing samples:  21%|██        | 25/120 [1:00:22<4:09:56, 157.86s/it]

 - Saved Pickle file in 5.994s
Finalized sample>M&A, top-tech, 90, 12q, caliper_0.0750, 10matches with 3861193 rows.

Processing 01 Hybrid matches - M&A, baseline, 12q, caliper_0.1000, 10matches.pkl
 - Loaded sample in 13.597s
 - Combined with citations in 252.481s
 -> Total process_sample time: 289.937s
 - Merged with patents metadata in 21.228s

Processing samples:  22%|██▏       | 26/120 [1:07:31<6:14:42, 239.17s/it]

 - Saved Pickle file in 96.101s
Finalized sample>M&A, baseline, 12q, caliper_0.1000, 10matches with 55829810 rows.

Processing 01 Hybrid matches - M&A, top-tech, 80, 4q, caliper_0.1000, 10matches.pkl
 - Loaded sample in 2.487s
 - Combined with citations in 63.797s
 -> Total process_sample time: 72.952s
 - Merged with patents metadata in 8.415s

Processing samples:  22%|██▎       | 27/120 [1:09:25<5:12:25, 201.56s/it]

 - Saved Pickle file in 26.130s
Finalized sample>M&A, top-tech, 80, 4q, caliper_0.1000, 10matches with 14889721 rows.

Processing 01 Hybrid matches - Off deal, baseline, 10q, caliper_0.0250, 10matches.pkl
 - Loaded sample in 2.808s
 - Combined with citations in 63.118s
 -> Total process_sample time: 70.218s
 - Merged with patents metadata in 6.792s

Processing samples:  23%|██▎       | 28/120 [1:11:11<4:25:01, 172.85s/it]

 - Saved Pickle file in 23.456s
Finalized sample>Off deal, baseline, 10q, caliper_0.0250, 10matches with 17705448 rows.

Processing 01 Hybrid matches - M&A, baseline, 4q, caliper_0.0750, 10matches.pkl
 - Loaded sample in 25.428s
 - Combined with citations in 240.174s
 -> Total process_sample time: 292.932s
 - Merged with patents metadata in 20.708s

Processing samples:  24%|██▍       | 29/120 [1:18:48<6:31:22, 258.05s/it]

 - Saved Pickle file in 123.348s
Finalized sample>M&A, baseline, 4q, caliper_0.0750, 10matches with 52138596 rows.

Processing 01 Hybrid matches - M&A, top-tech, 80, 10q, caliper_0.0250, 10matches.pkl
 - Loaded sample in 0.197s
 - Combined with citations in 5.871s
 -> Total process_sample time: 6.296s
 - Merged with patents metadata in 2.769s

Processing samples:  25%|██▌       | 30/120 [1:22:50<6:19:44, 253.17s/it]

 - Saved Pickle file in 231.379s
Finalized sample>M&A, top-tech, 80, 10q, caliper_0.0250, 10matches with 1632479 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 80, 4q, caliper_0.0500, 10matches.pkl
 - Loaded sample in 3.098s
 - Combined with citations in 73.709s
 -> Total process_sample time: 80.680s
 - Merged with patents metadata in 4.964s

Processing samples:  26%|██▌       | 31/120 [1:24:49<5:16:05, 213.09s/it]

 - Saved Pickle file in 27.016s
Finalized sample>Off deal, top-tech, 80, 4q, caliper_0.0500, 10matches with 12551615 rows.

Processing 01 Hybrid matches - Off deal, baseline, 6q, caliper_0.0500, 10matches.pkl
 - Loaded sample in 7.287s
 - Combined with citations in 136.596s
 -> Total process_sample time: 157.278s
 - Merged with patents metadata in 19.727s

Processing samples:  27%|██▋       | 32/120 [1:28:59<5:28:46, 224.16s/it]

 - Saved Pickle file in 58.356s
Finalized sample>Off deal, baseline, 6q, caliper_0.0500, 10matches with 37096351 rows.

Processing 01 Hybrid matches - M&A, baseline, 6q, caliper_0.0500, 10matches.pkl
 - Loaded sample in 7.964s
 - Combined with citations in 167.214s
 -> Total process_sample time: 199.700s
 - Merged with patents metadata in 15.478s

Processing samples:  28%|██▊       | 33/120 [1:33:51<5:54:17, 244.33s/it]

 - Saved Pickle file in 60.210s
Finalized sample>M&A, baseline, 6q, caliper_0.0500, 10matches with 36962884 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 80, 4q, caliper_0.0750, 10matches.pkl
 - Loaded sample in 5.715s
 - Combined with citations in 74.390s
 -> Total process_sample time: 86.586s
 - Merged with patents metadata in 7.657s

Processing samples:  28%|██▊       | 34/120 [1:35:54<4:58:13, 208.07s/it]

 - Saved Pickle file in 23.525s
Finalized sample>Off deal, top-tech, 80, 4q, caliper_0.0750, 10matches with 17082615 rows.

Processing 01 Hybrid matches - M&A, baseline, 10q, caliper_0.0500, 10matches.pkl
 - Loaded sample in 6.542s
 - Combined with citations in 137.544s
 -> Total process_sample time: 156.651s
 - Merged with patents metadata in 12.196s

Processing samples:  29%|██▉       | 35/120 [1:39:43<5:03:48, 214.46s/it]

 - Saved Pickle file in 49.136s
Finalized sample>M&A, baseline, 10q, caliper_0.0500, 10matches with 33011226 rows.

Processing 01 Hybrid matches - M&A, top-tech, 90, 8q, caliper_0.0500, 10matches.pkl
 - Loaded sample in 0.216s
 - Combined with citations in 7.026s
 -> Total process_sample time: 7.508s
 - Merged with patents metadata in 2.015s

Processing samples:  30%|███       | 36/120 [1:39:56<3:35:37, 154.02s/it]

 - Saved Pickle file in 2.430s
Finalized sample>M&A, top-tech, 90, 8q, caliper_0.0500, 10matches with 1905218 rows.

Processing 01 Hybrid matches - Off deal, baseline, 10q, caliper_0.0750, 10matches.pkl
 - Loaded sample in 9.961s
 - Combined with citations in 158.811s
 -> Total process_sample time: 192.524s
 - Merged with patents metadata in 16.578s

Processing samples:  31%|███       | 37/120 [1:45:24<4:45:06, 206.11s/it]

 - Saved Pickle file in 97.973s
Finalized sample>Off deal, baseline, 10q, caliper_0.0750, 10matches with 44375677 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 90, 4q, caliper_0.1000, 10matches.pkl
 - Loaded sample in 0.665s
 - Combined with citations in 22.941s
 -> Total process_sample time: 24.600s
 - Merged with patents metadata in 4.695s

Processing samples:  32%|███▏      | 38/120 [1:46:07<3:34:53, 157.24s/it]

 - Saved Pickle file in 10.834s
Finalized sample>Off deal, top-tech, 90, 4q, caliper_0.1000, 10matches with 6524855 rows.

Processing 01 Hybrid matches - Off deal, baseline, 6q, caliper_0.0250, 10matches.pkl
 - Loaded sample in 5.038s
 - Combined with citations in 85.343s
 -> Total process_sample time: 95.148s
 - Merged with patents metadata in 7.815s

Processing samples:  32%|███▎      | 39/120 [1:48:27<3:25:16, 152.05s/it]

 - Saved Pickle file in 29.410s
Finalized sample>Off deal, baseline, 6q, caliper_0.0250, 10matches with 21418030 rows.

Processing 01 Hybrid matches - M&A, top-tech, 90, 8q, caliper_0.0250, 10matches.pkl
 - Loaded sample in 0.093s
 - Combined with citations in 2.495s
 -> Total process_sample time: 2.681s
 - Merged with patents metadata in 0.968s

Processing samples:  33%|███▎      | 40/120 [1:48:32<2:23:52, 107.90s/it]

 - Saved Pickle file in 0.784s
Finalized sample>M&A, top-tech, 90, 8q, caliper_0.0250, 10matches with 613842 rows.

Processing 01 Hybrid matches - Off deal, baseline, 10q, caliper_0.0500, 10matches.pkl
 - Loaded sample in 7.398s
 - Combined with citations in 123.356s
 -> Total process_sample time: 141.782s
 - Merged with patents metadata in 13.093s

Processing samples:  34%|███▍      | 41/120 [1:52:14<3:06:57, 141.99s/it]

 - Saved Pickle file in 51.144s
Finalized sample>Off deal, baseline, 10q, caliper_0.0500, 10matches with 34861685 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 80, 8q, caliper_0.0250, 10matches.pkl
 - Loaded sample in 0.424s
 - Combined with citations in 10.079s
 -> Total process_sample time: 10.920s
 - Merged with patents metadata in 2.666s

Processing samples:  35%|███▌      | 42/120 [1:52:33<2:16:37, 105.10s/it]

 - Saved Pickle file in 4.084s
Finalized sample>Off deal, top-tech, 80, 8q, caliper_0.0250, 10matches with 3036007 rows.

Processing 01 Hybrid matches - Off deal, baseline, 12q, caliper_0.1000, 10matches.pkl
 - Loaded sample in 9.955s
 - Combined with citations in 183.319s
 -> Total process_sample time: 215.527s
 - Merged with patents metadata in 17.684s

Processing samples:  36%|███▌      | 43/120 [1:58:20<3:48:20, 177.93s/it]

 - Saved Pickle file in 94.305s
Finalized sample>Off deal, baseline, 12q, caliper_0.1000, 10matches with 47711347 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 80, 12q, caliper_0.0500, 10matches.pkl
 - Loaded sample in 1.041s
 - Combined with citations in 33.725s
 -> Total process_sample time: 36.769s
 - Merged with patents metadata in 5.438s

Processing samples:  37%|███▋      | 44/120 [1:59:22<3:01:15, 143.10s/it]

 - Saved Pickle file in 15.361s
Finalized sample>Off deal, top-tech, 80, 12q, caliper_0.0500, 10matches with 9546716 rows.

Processing 01 Hybrid matches - M&A, baseline, 8q, caliper_0.0500, 10matches.pkl
 - Loaded sample in 8.488s
 - Combined with citations in 141.970s
 -> Total process_sample time: 167.889s
 - Merged with patents metadata in 14.155s

Processing samples:  38%|███▊      | 45/120 [2:03:35<3:39:55, 175.94s/it]

 - Saved Pickle file in 55.946s
Finalized sample>M&A, baseline, 8q, caliper_0.0500, 10matches with 34602467 rows.

Processing 01 Hybrid matches - Off deal, baseline, 8q, caliper_0.0750, 10matches.pkl
 - Loaded sample in 7.306s
 - Combined with citations in 191.652s
 -> Total process_sample time: 219.851s
 - Merged with patents metadata in 20.978s

Processing samples:  38%|███▊      | 46/120 [2:09:08<4:35:07, 223.07s/it]

 - Saved Pickle file in 75.922s
Finalized sample>Off deal, baseline, 8q, caliper_0.0750, 10matches with 45010677 rows.

Processing 01 Hybrid matches - M&A, top-tech, 80, 10q, caliper_0.0750, 10matches.pkl
 - Loaded sample in 1.642s
 - Combined with citations in 38.234s
 -> Total process_sample time: 41.654s
 - Merged with patents metadata in 5.338s

Processing samples:  39%|███▉      | 47/120 [2:10:17<3:35:10, 176.85s/it]

 - Saved Pickle file in 18.154s
Finalized sample>M&A, top-tech, 80, 10q, caliper_0.0750, 10matches with 9032343 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 90, 6q, caliper_0.0250, 10matches.pkl
 - Loaded sample in 0.154s
 - Combined with citations in 4.266s
 -> Total process_sample time: 4.586s
 - Merged with patents metadata in 0.656s

Processing samples:  40%|████      | 48/120 [2:10:24<2:31:10, 125.98s/it]

 - Saved Pickle file in 1.612s
Finalized sample>Off deal, top-tech, 90, 6q, caliper_0.0250, 10matches with 992927 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 90, 8q, caliper_0.1000, 10matches.pkl
 - Loaded sample in 1.852s
 - Combined with citations in 28.967s
 -> Total process_sample time: 32.055s
 - Merged with patents metadata in 1.918s

Processing samples:  41%|████      | 49/120 [2:11:09<2:00:23, 101.74s/it]

 - Saved Pickle file in 9.872s
Finalized sample>Off deal, top-tech, 90, 8q, caliper_0.1000, 10matches with 6974216 rows.

Processing 01 Hybrid matches - Off deal, baseline, 12q, caliper_0.0750, 10matches.pkl
 - Loaded sample in 8.210s
 - Combined with citations in 149.624s
 -> Total process_sample time: 181.230s
 - Merged with patents metadata in 17.983s

Processing samples:  42%|████▏     | 50/120 [2:16:31<3:15:28, 167.55s/it]

 - Saved Pickle file in 101.202s
Finalized sample>Off deal, baseline, 12q, caliper_0.0750, 10matches with 43318039 rows.

Processing 01 Hybrid matches - M&A, top-tech, 80, 6q, caliper_0.0750, 10matches.pkl
 - Loaded sample in 0.929s
 - Combined with citations in 31.955s
 -> Total process_sample time: 34.388s
 - Merged with patents metadata in 4.539s

Processing samples:  42%|████▎     | 51/120 [2:17:26<2:34:11, 134.07s/it]

 - Saved Pickle file in 13.826s
Finalized sample>M&A, top-tech, 80, 6q, caliper_0.0750, 10matches with 7927891 rows.

Processing 01 Hybrid matches - M&A, baseline, 10q, caliper_0.0750, 10matches.pkl
 - Loaded sample in 12.678s
 - Combined with citations in 199.458s
 -> Total process_sample time: 237.566s
 - Merged with patents metadata in 18.575s

Processing samples:  43%|████▎     | 52/120 [2:23:35<3:51:35, 204.34s/it]

 - Saved Pickle file in 89.959s
Finalized sample>M&A, baseline, 10q, caliper_0.0750, 10matches with 47457176 rows.

Processing 01 Hybrid matches - M&A, top-tech, 90, 6q, caliper_0.0750, 10matches.pkl
 - Loaded sample in 0.505s
 - Combined with citations in 18.016s
 -> Total process_sample time: 19.252s
 - Merged with patents metadata in 4.057s

Processing samples:  44%|████▍     | 53/120 [2:24:08<2:51:01, 153.15s/it]

 - Saved Pickle file in 7.936s
Finalized sample>M&A, top-tech, 90, 6q, caliper_0.0750, 10matches with 3974976 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 90, 12q, caliper_0.1000, 10matches.pkl
 - Loaded sample in 1.659s
 - Combined with citations in 28.131s
 -> Total process_sample time: 30.871s
 - Merged with patents metadata in 2.798s

Processing samples:  45%|████▌     | 54/120 [2:24:58<2:14:07, 121.94s/it]

 - Saved Pickle file in 13.729s
Finalized sample>Off deal, top-tech, 90, 12q, caliper_0.1000, 10matches with 7321554 rows.

Processing 01 Hybrid matches - M&A, baseline, 4q, caliper_0.0500, 10matches.pkl
 - Loaded sample in 13.888s
 - Combined with citations in 200.095s
 -> Total process_sample time: 233.038s
 - Merged with patents metadata in 16.450s

Processing samples:  46%|████▌     | 55/120 [2:30:50<3:26:55, 191.01s/it]

 - Saved Pickle file in 83.645s
Finalized sample>M&A, baseline, 4q, caliper_0.0500, 10matches with 40261059 rows.

Processing 01 Hybrid matches - M&A, top-tech, 80, 8q, caliper_0.0750, 10matches.pkl
 - Loaded sample in 0.977s
 - Combined with citations in 36.630s
 -> Total process_sample time: 38.915s
 - Merged with patents metadata in 5.223s

Processing samples:  47%|████▋     | 56/120 [2:31:55<2:43:36, 153.38s/it]

 - Saved Pickle file in 17.668s
Finalized sample>M&A, top-tech, 80, 8q, caliper_0.0750, 10matches with 8613979 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 80, 8q, caliper_0.0500, 10matches.pkl
 - Loaded sample in 2.875s
 - Combined with citations in 37.511s
 -> Total process_sample time: 41.685s
 - Merged with patents metadata in 2.928s

Processing samples:  48%|████▊     | 57/120 [2:32:59<2:12:55, 126.60s/it]

 - Saved Pickle file in 16.203s
Finalized sample>Off deal, top-tech, 80, 8q, caliper_0.0500, 10matches with 9601037 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 90, 12q, caliper_0.0250, 10matches.pkl
 - Loaded sample in 0.152s
 - Combined with citations in 4.089s
 -> Total process_sample time: 4.402s
 - Merged with patents metadata in 0.652s

Processing samples:  48%|████▊     | 58/120 [2:33:06<1:33:43, 90.70s/it]

 - Saved Pickle file in 1.517s
Finalized sample>Off deal, top-tech, 90, 12q, caliper_0.0250, 10matches with 1190583 rows.

Processing 01 Hybrid matches - M&A, top-tech, 90, 8q, caliper_0.1000, 10matches.pkl
 - Loaded sample in 1.300s
 - Combined with citations in 22.030s
 -> Total process_sample time: 24.073s
 - Merged with patents metadata in 1.521s

Processing samples:  49%|████▉     | 59/120 [2:33:42<1:15:16, 74.05s/it]

 - Saved Pickle file in 8.529s
Finalized sample>M&A, top-tech, 90, 8q, caliper_0.1000, 10matches with 4938564 rows.

Processing 01 Hybrid matches - M&A, baseline, 6q, caliper_0.0250, 10matches.pkl
 - Loaded sample in 5.290s
 - Combined with citations in 90.566s
 -> Total process_sample time: 101.957s
 - Merged with patents metadata in 8.153s

Processing samples:  50%|█████     | 60/120 [2:36:21<1:39:34, 99.58s/it]

 - Saved Pickle file in 37.935s
Finalized sample>M&A, baseline, 6q, caliper_0.0250, 10matches with 19999018 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 80, 4q, caliper_0.1000, 10matches.pkl
 - Loaded sample in 4.795s
 - Combined with citations in 94.160s
 -> Total process_sample time: 106.599s
 - Merged with patents metadata in 8.515s

Processing samples:  51%|█████     | 61/120 [2:39:12<1:59:09, 121.18s/it]

 - Saved Pickle file in 47.658s
Finalized sample>Off deal, top-tech, 80, 4q, caliper_0.1000, 10matches with 19312090 rows.

Processing 01 Hybrid matches - Off deal, baseline, 6q, caliper_0.0750, 10matches.pkl
 - Loaded sample in 10.128s
 - Combined with citations in 173.687s
 -> Total process_sample time: 205.600s
 - Merged with patents metadata in 19.698s

Processing samples:  52%|█████▏    | 62/120 [2:44:49<2:59:38, 185.84s/it]

 - Saved Pickle file in 88.218s
Finalized sample>Off deal, baseline, 6q, caliper_0.0750, 10matches with 45580419 rows.

Processing 01 Hybrid matches - Off deal, baseline, 12q, caliper_0.0500, 10matches.pkl
 - Loaded sample in 4.061s
 - Combined with citations in 141.762s
 -> Total process_sample time: 183.162s
 - Merged with patents metadata in 15.828s

Processing samples:  52%|█████▎    | 63/120 [2:49:24<3:22:04, 212.71s/it]

 - Saved Pickle file in 57.406s
Finalized sample>Off deal, baseline, 12q, caliper_0.0500, 10matches with 33471128 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 90, 12q, caliper_0.0500, 10matches.pkl
 - Loaded sample in 0.388s
 - Combined with citations in 13.111s
 -> Total process_sample time: 14.097s
 - Merged with patents metadata in 2.654s

Processing samples:  53%|█████▎    | 64/120 [2:49:50<2:26:04, 156.50s/it]

 - Saved Pickle file in 7.101s
Finalized sample>Off deal, top-tech, 90, 12q, caliper_0.0500, 10matches with 3866686 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 90, 6q, caliper_0.0750, 10matches.pkl
 - Loaded sample in 1.335s
 - Combined with citations in 21.276s
 -> Total process_sample time: 23.472s
 - Merged with patents metadata in 2.048s

Processing samples:  54%|█████▍    | 65/120 [2:50:28<1:50:49, 120.90s/it]

 - Saved Pickle file in 11.047s
Finalized sample>Off deal, top-tech, 90, 6q, caliper_0.0750, 10matches with 5589841 rows.

Processing 01 Hybrid matches - Off deal, baseline, 8q, caliper_0.0500, 10matches.pkl
 - Loaded sample in 9.439s
 - Combined with citations in 131.969s
 -> Total process_sample time: 150.259s
 - Merged with patents metadata in 13.835s

Processing samples:  55%|█████▌    | 66/120 [2:54:29<2:21:18, 157.01s/it]

 - Saved Pickle file in 64.643s
Finalized sample>Off deal, baseline, 8q, caliper_0.0500, 10matches with 35921484 rows.

Processing 01 Hybrid matches - M&A, top-tech, 90, 4q, caliper_0.1000, 10matches.pkl
 - Loaded sample in 0.745s
 - Combined with citations in 23.184s
 -> Total process_sample time: 24.792s
 - Merged with patents metadata in 3.227s

Processing samples:  56%|█████▌    | 67/120 [2:55:12<1:48:29, 122.83s/it]

 - Saved Pickle file in 13.008s
Finalized sample>M&A, top-tech, 90, 4q, caliper_0.1000, 10matches with 5496561 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 90, 10q, caliper_0.1000, 10matches.pkl
 - Loaded sample in 3.805s
 - Combined with citations in 35.575s
 -> Total process_sample time: 40.447s
 - Merged with patents metadata in 2.489s

Processing samples:  57%|█████▋    | 68/120 [2:56:09<1:29:18, 103.05s/it]

 - Saved Pickle file in 12.340s
Finalized sample>Off deal, top-tech, 90, 10q, caliper_0.1000, 10matches with 7241085 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 90, 10q, caliper_0.0750, 10matches.pkl
 - Loaded sample in 0.982s
 - Combined with citations in 21.983s
 -> Total process_sample time: 24.037s
 - Merged with patents metadata in 2.164s

Processing samples:  57%|█████▊    | 69/120 [2:56:45<1:10:37, 83.08s/it]

 - Saved Pickle file in 8.938s
Finalized sample>Off deal, top-tech, 90, 10q, caliper_0.0750, 10matches with 6103433 rows.

Processing 01 Hybrid matches - Off deal, baseline, 12q, caliper_0.0250, 10matches.pkl
 - Loaded sample in 3.385s
 - Combined with citations in 61.932s
 -> Total process_sample time: 71.442s
 - Merged with patents metadata in 11.214s

Processing samples:  58%|█████▊    | 70/120 [2:59:05<1:23:19, 99.99s/it]

 - Saved Pickle file in 44.548s
Finalized sample>Off deal, baseline, 12q, caliper_0.0250, 10matches with 16182657 rows.

Processing 01 Hybrid matches - M&A, top-tech, 80, 4q, caliper_0.0750, 10matches.pkl
 - Loaded sample in 2.398s
 - Combined with citations in 49.289s
 -> Total process_sample time: 54.464s
 - Merged with patents metadata in 4.605s

Processing samples:  59%|█████▉    | 71/120 [3:00:32<1:18:30, 96.14s/it]

 - Saved Pickle file in 23.298s
Finalized sample>M&A, top-tech, 80, 4q, caliper_0.0750, 10matches with 11455653 rows.

Processing 01 Hybrid matches - Off deal, baseline, 8q, caliper_0.0250, 10matches.pkl
 - Loaded sample in 4.138s
 - Combined with citations in 73.274s
 -> Total process_sample time: 81.762s
 - Merged with patents metadata in 8.222s

Processing samples:  60%|██████    | 72/120 [3:02:44<1:25:37, 107.03s/it]

 - Saved Pickle file in 35.049s
Finalized sample>Off deal, baseline, 8q, caliper_0.0250, 10matches with 19399490 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 90, 4q, caliper_0.0750, 10matches.pkl
 - Loaded sample in 0.611s
 - Combined with citations in 18.177s
 -> Total process_sample time: 19.595s
 - Merged with patents metadata in 2.656s

Processing samples:  61%|██████    | 73/120 [3:03:19<1:06:44, 85.21s/it]

 - Saved Pickle file in 10.577s
Finalized sample>Off deal, top-tech, 90, 4q, caliper_0.0750, 10matches with 5305375 rows.

Processing 01 Hybrid matches - Off deal, baseline, 6q, caliper_0.1000, 10matches.pkl
 - Loaded sample in 13.567s
 - Combined with citations in 188.198s
 -> Total process_sample time: 218.677s
 - Merged with patents metadata in 20.405s

Processing samples:  62%|██████▏   | 74/120 [3:09:33<2:11:46, 171.87s/it]

 - Saved Pickle file in 114.617s
Finalized sample>Off deal, baseline, 6q, caliper_0.1000, 10matches with 49404857 rows.

Processing 01 Hybrid matches - M&A, baseline, 10q, caliper_0.1000, 10matches.pkl
 - Loaded sample in 12.249s
 - Combined with citations in 248.171s
 -> Total process_sample time: 301.538s
 - Merged with patents metadata in 23.870s

Processing samples:  62%|██████▎   | 75/120 [3:17:21<3:15:41, 260.92s/it]

 - Saved Pickle file in 118.744s
Finalized sample>M&A, baseline, 10q, caliper_0.1000, 10matches with 56388041 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 90, 6q, caliper_0.1000, 10matches.pkl
 - Loaded sample in 0.903s
 - Combined with citations in 26.974s
 -> Total process_sample time: 29.139s
 - Merged with patents metadata in 4.967s

Processing samples:  63%|██████▎   | 76/120 [3:18:12<2:25:06, 197.88s/it]

 - Saved Pickle file in 13.276s
Finalized sample>Off deal, top-tech, 90, 6q, caliper_0.1000, 10matches with 6788954 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 80, 8q, caliper_0.0750, 10matches.pkl
 - Loaded sample in 3.063s
 - Combined with citations in 56.481s
 -> Total process_sample time: 61.919s
 - Merged with patents metadata in 8.720s

Processing samples:  64%|██████▍   | 77/120 [3:20:11<2:04:47, 174.13s/it]

 - Saved Pickle file in 43.390s
Finalized sample>Off deal, top-tech, 80, 8q, caliper_0.0750, 10matches with 14327673 rows.

Processing 01 Hybrid matches - M&A, baseline, 12q, caliper_0.0250, 10matches.pkl
 - Loaded sample in 2.863s
 - Combined with citations in 63.111s
 -> Total process_sample time: 69.826s
 - Merged with patents metadata in 5.734s

Processing samples:  65%|██████▌   | 78/120 [3:22:00<1:48:10, 154.54s/it]

 - Saved Pickle file in 26.811s
Finalized sample>M&A, baseline, 12q, caliper_0.0250, 10matches with 14719463 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 80, 10q, caliper_0.0250, 10matches.pkl
 - Loaded sample in 0.268s
 - Combined with citations in 8.120s
 -> Total process_sample time: 8.729s
 - Merged with patents metadata in 1.430s

Processing samples:  66%|██████▌   | 79/120 [3:22:15<1:16:57, 112.62s/it]

 - Saved Pickle file in 3.893s
Finalized sample>Off deal, top-tech, 80, 10q, caliper_0.0250, 10matches with 2452374 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 90, 10q, caliper_0.0250, 10matches.pkl
 - Loaded sample in 0.438s
 - Combined with citations in 4.753s
 -> Total process_sample time: 5.387s
 - Merged with patents metadata in 0.553s

Processing samples:  67%|██████▋   | 80/120 [3:22:23<54:09, 81.24s/it]

 - Saved Pickle file in 1.786s
Finalized sample>Off deal, top-tech, 90, 10q, caliper_0.0250, 10matches with 1160291 rows.

Processing 01 Hybrid matches - M&A, baseline, 10q, caliper_0.0250, 10matches.pkl
 - Loaded sample in 4.496s
 - Combined with citations in 65.415s
 -> Total process_sample time: 72.153s
 - Merged with patents metadata in 4.885s

Processing samples:  68%|██████▊   | 81/120 [3:24:09<57:44, 88.84s/it]

 - Saved Pickle file in 24.635s
Finalized sample>M&A, baseline, 10q, caliper_0.0250, 10matches with 15916479 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 90, 6q, caliper_0.0500, 10matches.pkl
 - Loaded sample in 0.397s
 - Combined with citations in 13.420s
 -> Total process_sample time: 14.631s
 - Merged with patents metadata in 3.775s

Processing samples:  68%|██████▊   | 82/120 [3:24:35<44:16, 69.90s/it]

 - Saved Pickle file in 5.150s
Finalized sample>Off deal, top-tech, 90, 6q, caliper_0.0500, 10matches with 3316855 rows.

Processing 01 Hybrid matches - M&A, baseline, 8q, caliper_0.0250, 10matches.pkl
 - Loaded sample in 4.891s
 - Combined with citations in 75.053s
 -> Total process_sample time: 83.174s
 - Merged with patents metadata in 6.106s

Processing samples:  69%|██████▉   | 83/120 [3:26:36<52:32, 85.22s/it]

 - Saved Pickle file in 24.934s
Finalized sample>M&A, baseline, 8q, caliper_0.0250, 10matches with 17738453 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 90, 8q, caliper_0.0750, 10matches.pkl
 - Loaded sample in 0.708s
 - Combined with citations in 21.734s
 -> Total process_sample time: 23.271s
 - Merged with patents metadata in 2.738s

Processing samples:  70%|███████   | 84/120 [3:27:13<42:28, 70.80s/it]

 - Saved Pickle file in 9.621s
Finalized sample>Off deal, top-tech, 90, 8q, caliper_0.0750, 10matches with 5842659 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 80, 6q, caliper_0.1000, 10matches.pkl
 - Loaded sample in 2.719s
 - Combined with citations in 51.071s
 -> Total process_sample time: 55.966s
 - Merged with patents metadata in 4.425s

Processing samples:  71%|███████   | 85/120 [3:28:43<44:35, 76.45s/it]

 - Saved Pickle file in 24.883s
Finalized sample>Off deal, top-tech, 80, 6q, caliper_0.1000, 10matches with 13211806 rows.

Processing 01 Hybrid matches - M&A, top-tech, 90, 6q, caliper_0.0500, 10matches.pkl
 - Loaded sample in 0.618s
 - Combined with citations in 8.560s
 -> Total process_sample time: 9.609s
 - Merged with patents metadata in 1.118s

Processing samples:  72%|███████▏  | 86/120 [3:28:58<32:55, 58.10s/it]

 - Saved Pickle file in 3.861s
Finalized sample>M&A, top-tech, 90, 6q, caliper_0.0500, 10matches with 2132969 rows.

Processing 01 Hybrid matches - M&A, top-tech, 90, 4q, caliper_0.0750, 10matches.pkl
 - Loaded sample in 0.911s
 - Combined with citations in 17.771s
 -> Total process_sample time: 19.251s
 - Merged with patents metadata in 1.156s

Processing samples:  72%|███████▎  | 87/120 [3:29:27<27:05, 49.26s/it]

 - Saved Pickle file in 7.429s
Finalized sample>M&A, top-tech, 90, 4q, caliper_0.0750, 10matches with 3977124 rows.

Processing 01 Hybrid matches - M&A, top-tech, 80, 12q, caliper_0.0500, 10matches.pkl
 - Loaded sample in 0.901s
 - Combined with citations in 19.551s
 -> Total process_sample time: 21.178s
 - Merged with patents metadata in 1.572s

Processing samples:  73%|███████▎  | 88/120 [3:30:07<24:50, 46.59s/it]

 - Saved Pickle file in 16.505s
Finalized sample>M&A, top-tech, 80, 12q, caliper_0.0500, 10matches with 5226801 rows.

Processing 01 Hybrid matches - M&A, top-tech, 80, 12q, caliper_0.0750, 10matches.pkl
 - Loaded sample in 3.886s
 - Combined with citations in 43.248s
 -> Total process_sample time: 48.392s
 - Merged with patents metadata in 2.676s

Processing samples:  74%|███████▍  | 89/120 [3:31:21<28:23, 54.94s/it]

 - Saved Pickle file in 20.250s
Finalized sample>M&A, top-tech, 80, 12q, caliper_0.0750, 10matches with 9187102 rows.

Processing 01 Hybrid matches - M&A, top-tech, 90, 12q, caliper_0.0250, 10matches.pkl
 - Loaded sample in 0.092s
 - Combined with citations in 2.649s
 -> Total process_sample time: 2.843s
 - Merged with patents metadata in 0.451s

Processing samples:  75%|███████▌  | 90/120 [3:31:26<19:53, 39.79s/it]

 - Saved Pickle file in 0.879s
Finalized sample>M&A, top-tech, 90, 12q, caliper_0.0250, 10matches with 652764 rows.

Processing 01 Hybrid matches - M&A, baseline, 12q, caliper_0.0750, 10matches.pkl
 - Loaded sample in 12.068s
 - Combined with citations in 176.793s
 -> Total process_sample time: 206.535s
 - Merged with patents metadata in 17.535s

Processing samples:  76%|███████▌  | 91/120 [3:36:48<1:00:14, 124.64s/it]

 - Saved Pickle file in 77.914s
Finalized sample>M&A, baseline, 12q, caliper_0.0750, 10matches with 46491025 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 80, 12q, caliper_0.0750, 10matches.pkl
 - Loaded sample in 1.782s
 - Combined with citations in 53.861s
 -> Total process_sample time: 60.678s
 - Merged with patents metadata in 7.714s

Processing samples:  77%|███████▋  | 92/120 [3:38:27<54:29, 116.78s/it]

 - Saved Pickle file in 24.427s
Finalized sample>Off deal, top-tech, 80, 12q, caliper_0.0750, 10matches with 14197948 rows.

Processing 01 Hybrid matches - M&A, top-tech, 80, 12q, caliper_0.1000, 10matches.pkl
 - Loaded sample in 2.380s
 - Combined with citations in 46.908s
 -> Total process_sample time: 51.075s
 - Merged with patents metadata in 4.370s

Processing samples:  78%|███████▊  | 93/120 [3:39:43<47:05, 104.66s/it]

 - Saved Pickle file in 17.222s
Finalized sample>M&A, top-tech, 80, 12q, caliper_0.1000, 10matches with 12150882 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 90, 4q, caliper_0.0500, 10matches.pkl
 - Loaded sample in 0.334s
 - Combined with citations in 10.971s
 -> Total process_sample time: 11.783s
 - Merged with patents metadata in 1.823s

Processing samples:  78%|███████▊  | 94/120 [3:40:03<34:22, 79.31s/it]

 - Saved Pickle file in 5.488s
Finalized sample>Off deal, top-tech, 90, 4q, caliper_0.0500, 10matches with 3169125 rows.

Processing 01 Hybrid matches - M&A, top-tech, 90, 10q, caliper_0.0500, 10matches.pkl
 - Loaded sample in 0.451s
 - Combined with citations in 9.661s
 -> Total process_sample time: 10.429s
 - Merged with patents metadata in 0.786s

Processing samples:  79%|███████▉  | 95/120 [3:40:18<25:00, 60.02s/it]

 - Saved Pickle file in 3.302s
Finalized sample>M&A, top-tech, 90, 10q, caliper_0.0500, 10matches with 2063001 rows.

Processing 01 Hybrid matches - M&A, top-tech, 90, 8q, caliper_0.0750, 10matches.pkl
 - Loaded sample in 0.924s
 - Combined with citations in 17.375s
 -> Total process_sample time: 19.309s
 - Merged with patents metadata in 2.137s

Processing samples:  80%|████████  | 96/120 [3:40:56<21:18, 53.28s/it]

 - Saved Pickle file in 14.680s
Finalized sample>M&A, top-tech, 90, 8q, caliper_0.0750, 10matches with 3564751 rows.

Processing 01 Hybrid matches - M&A, top-tech, 80, 10q, caliper_0.1000, 10matches.pkl
 - Loaded sample in 5.757s
 - Combined with citations in 54.869s
 -> Total process_sample time: 62.370s
 - Merged with patents metadata in 3.377s

Processing samples:  81%|████████  | 97/120 [3:42:40<26:15, 68.48s/it]

 - Saved Pickle file in 31.932s
Finalized sample>M&A, top-tech, 80, 10q, caliper_0.1000, 10matches with 11921239 rows.

Processing 01 Hybrid matches - M&A, top-tech, 90, 10q, caliper_0.1000, 10matches.pkl
 - Loaded sample in 0.959s
 - Combined with citations in 20.974s
 -> Total process_sample time: 22.729s
 - Merged with patents metadata in 2.018s

Processing samples:  82%|████████▏ | 98/120 [3:43:16<21:31, 58.72s/it]

 - Saved Pickle file in 9.963s
Finalized sample>M&A, top-tech, 90, 10q, caliper_0.1000, 10matches with 5348450 rows.

Processing 01 Hybrid matches - M&A, top-tech, 80, 6q, caliper_0.0250, 10matches.pkl
 - Loaded sample in 0.228s
 - Combined with citations in 5.742s
 -> Total process_sample time: 6.232s
 - Merged with patents metadata in 0.689s

Processing samples:  82%|████████▎ | 99/120 [3:43:26<15:24, 44.04s/it]

 - Saved Pickle file in 2.501s
Finalized sample>M&A, top-tech, 80, 6q, caliper_0.0250, 10matches with 1408645 rows.

Processing 01 Hybrid matches - M&A, top-tech, 90, 4q, caliper_0.0250, 10matches.pkl
 - Loaded sample in 0.145s
 - Combined with citations in 3.804s
 -> Total process_sample time: 4.060s
 - Merged with patents metadata in 0.262s

Processing samples:  83%|████████▎ | 100/120 [3:43:31<10:50, 32.55s/it]

 - Saved Pickle file in 1.258s
Finalized sample>M&A, top-tech, 90, 4q, caliper_0.0250, 10matches with 706658 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 90, 4q, caliper_0.0250, 10matches.pkl
 - Loaded sample in 0.335s
 - Combined with citations in 4.294s
 -> Total process_sample time: 4.779s
 - Merged with patents metadata in 0.313s

Processing samples:  84%|████████▍ | 101/120 [3:43:38<07:51, 24.79s/it]

 - Saved Pickle file in 1.397s
Finalized sample>Off deal, top-tech, 90, 4q, caliper_0.0250, 10matches with 1016210 rows.

Processing 01 Hybrid matches - Off deal, baseline, 4q, caliper_0.0500, 10matches.pkl
 - Loaded sample in 10.257s
 - Combined with citations in 143.026s
 -> Total process_sample time: 170.581s
 - Merged with patents metadata in 14.961s

Processing samples:  85%|████████▌ | 102/120 [3:48:08<29:28, 98.22s/it]

 - Saved Pickle file in 69.141s
Finalized sample>Off deal, baseline, 4q, caliper_0.0500, 10matches with 38742370 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 90, 8q, caliper_0.0500, 10matches.pkl
 - Loaded sample in 0.371s
 - Combined with citations in 12.423s
 -> Total process_sample time: 13.347s
 - Merged with patents metadata in 3.048s

Processing samples:  86%|████████▌ | 103/120 [3:48:33<21:38, 76.40s/it]

 - Saved Pickle file in 7.508s
Finalized sample>Off deal, top-tech, 90, 8q, caliper_0.0500, 10matches with 3631448 rows.

Processing 01 Hybrid matches - M&A, baseline, 6q, caliper_0.0750, 10matches.pkl
 - Loaded sample in 14.783s
 - Combined with citations in 248.392s
 -> Total process_sample time: 288.851s
 - Merged with patents metadata in 18.988s

Processing samples:  87%|████████▋ | 104/120 [3:55:39<48:20, 181.28s/it]

 - Saved Pickle file in 96.985s
Finalized sample>M&A, baseline, 6q, caliper_0.0750, 10matches with 50014911 rows.

Processing 01 Hybrid matches - M&A, baseline, 8q, caliper_0.1000, 10matches.pkl
 - Loaded sample in 13.440s
 - Combined with citations in 260.634s
 -> Total process_sample time: 311.733s
 - Merged with patents metadata in 51.653s

Processing samples:  88%|████████▊ | 105/120 [4:04:09<1:09:57, 279.84s/it]

 - Saved Pickle file in 122.315s
Finalized sample>M&A, baseline, 8q, caliper_0.1000, 10matches with 57117816 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 80, 12q, caliper_0.1000, 10matches.pkl
 - Loaded sample in 1.559s
 - Combined with citations in 61.568s
 -> Total process_sample time: 69.006s
 - Merged with patents metadata in 9.415s

Processing samples:  88%|████████▊ | 106/120 [4:06:01<53:32, 229.46s/it]

 - Saved Pickle file in 27.261s
Finalized sample>Off deal, top-tech, 80, 12q, caliper_0.1000, 10matches with 16281057 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 90, 8q, caliper_0.0250, 10matches.pkl
 - Loaded sample in 0.156s
 - Combined with citations in 4.350s
 -> Total process_sample time: 4.687s
 - Merged with patents metadata in 1.018s

Processing samples:  89%|████████▉ | 107/120 [4:06:09<35:19, 163.01s/it]

 - Saved Pickle file in 1.694s
Finalized sample>Off deal, top-tech, 90, 8q, caliper_0.0250, 10matches with 1112145 rows.

Processing 01 Hybrid matches - M&A, baseline, 4q, caliper_0.0250, 10matches.pkl
 - Loaded sample in 8.855s
 - Combined with citations in 104.774s
 -> Total process_sample time: 118.294s
 - Merged with patents metadata in 8.100s

Processing samples:  90%|█████████ | 108/120 [4:09:03<33:15, 166.28s/it]

 - Saved Pickle file in 40.469s
Finalized sample>M&A, baseline, 4q, caliper_0.0250, 10matches with 23462983 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 80, 10q, caliper_0.0750, 10matches.pkl
 - Loaded sample in 1.413s
 - Combined with citations in 43.842s
 -> Total process_sample time: 48.638s
 - Merged with patents metadata in 7.770s

Processing samples:  91%|█████████ | 109/120 [4:10:25<25:52, 141.13s/it]

 - Saved Pickle file in 21.672s
Finalized sample>Off deal, top-tech, 80, 10q, caliper_0.0750, 10matches with 12136122 rows.

Processing 01 Hybrid matches - M&A, top-tech, 80, 6q, caliper_0.1000, 10matches.pkl
 - Loaded sample in 2.017s
 - Combined with citations in 42.093s
 -> Total process_sample time: 45.592s
 - Merged with patents metadata in 3.572s

Processing samples:  92%|█████████▏| 110/120 [4:11:34<19:53, 119.32s/it]

 - Saved Pickle file in 16.067s
Finalized sample>M&A, top-tech, 80, 6q, caliper_0.1000, 10matches with 10585173 rows.

Processing 01 Hybrid matches - M&A, top-tech, 80, 12q, caliper_0.0250, 10matches.pkl
 - Loaded sample in 0.214s
 - Combined with citations in 6.262s
 -> Total process_sample time: 6.725s
 - Merged with patents metadata in 0.928s

Processing samples:  92%|█████████▎| 111/120 [4:11:45<13:01, 86.87s/it]

 - Saved Pickle file in 2.960s
Finalized sample>M&A, top-tech, 80, 12q, caliper_0.0250, 10matches with 1671297 rows.

Processing 01 Hybrid matches - M&A, top-tech, 90, 4q, caliper_0.0500, 10matches.pkl
 - Loaded sample in 0.510s
 - Combined with citations in 9.679s
 -> Total process_sample time: 10.566s
 - Merged with patents metadata in 0.928s

Processing samples:  93%|█████████▎| 112/120 [4:12:01<08:45, 65.65s/it]

 - Saved Pickle file in 4.044s
Finalized sample>M&A, top-tech, 90, 4q, caliper_0.0500, 10matches with 2115454 rows.

Processing 01 Hybrid matches - M&A, top-tech, 80, 4q, caliper_0.0250, 10matches.pkl
 - Loaded sample in 0.831s
 - Combined with citations in 10.680s
 -> Total process_sample time: 11.855s
 - Merged with patents metadata in 0.762s

Processing samples:  94%|█████████▍| 113/120 [4:12:17<05:55, 50.86s/it]

 - Saved Pickle file in 3.203s
Finalized sample>M&A, top-tech, 80, 4q, caliper_0.0250, 10matches with 2445419 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 80, 6q, caliper_0.0500, 10matches.pkl
 - Loaded sample in 1.529s
 - Combined with citations in 25.564s
 -> Total process_sample time: 28.109s
 - Merged with patents metadata in 3.813s

Processing samples:  95%|█████████▌| 114/120 [4:13:16<05:18, 53.17s/it]

 - Saved Pickle file in 24.589s
Finalized sample>Off deal, top-tech, 80, 6q, caliper_0.0500, 10matches with 7423613 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 90, 12q, caliper_0.0750, 10matches.pkl
 - Loaded sample in 2.153s
 - Combined with citations in 25.273s
 -> Total process_sample time: 28.287s
 - Merged with patents metadata in 1.937s

Processing samples:  96%|█████████▌| 115/120 [4:14:01<04:14, 50.82s/it]

 - Saved Pickle file in 13.530s
Finalized sample>Off deal, top-tech, 90, 12q, caliper_0.0750, 10matches with 6190597 rows.

Processing 01 Hybrid matches - M&A, top-tech, 90, 12q, caliper_0.1000, 10matches.pkl
 - Loaded sample in 1.529s
 - Combined with citations in 24.944s
 -> Total process_sample time: 27.201s
 - Merged with patents metadata in 1.670s

Processing samples:  97%|█████████▋| 116/120 [4:14:41<03:09, 47.48s/it]

 - Saved Pickle file in 9.718s
Finalized sample>M&A, top-tech, 90, 12q, caliper_0.1000, 10matches with 5384667 rows.

Processing 01 Hybrid matches - Off deal, top-tech, 80, 8q, caliper_0.1000, 10matches.pkl
 - Loaded sample in 3.341s
 - Combined with citations in 55.332s
 -> Total process_sample time: 62.877s
 - Merged with patents metadata in 6.046s

Processing samples:  98%|█████████▊| 117/120 [4:16:26<03:14, 64.70s/it]

 - Saved Pickle file in 29.140s
Finalized sample>Off deal, top-tech, 80, 8q, caliper_0.1000, 10matches with 16528972 rows.

Processing 01 Hybrid matches - Off deal, baseline, 8q, caliper_0.1000, 10matches.pkl
 - Loaded sample in 9.277s
 - Combined with citations in 181.103s
 -> Total process_sample time: 215.677s
 - Merged with patents metadata in 20.567s

Processing samples:  98%|█████████▊| 118/120 [4:22:11<04:57, 148.92s/it]

 - Saved Pickle file in 88.834s
Finalized sample>Off deal, baseline, 8q, caliper_0.1000, 10matches with 49045081 rows.

Processing 01 Hybrid matches - M&A, top-tech, 80, 4q, caliper_0.0500, 10matches.pkl
 - Loaded sample in 0.865s
 - Combined with citations in 27.423s
 -> Total process_sample time: 29.243s
 - Merged with patents metadata in 4.684s

Processing samples:  99%|█████████▉| 119/120 [4:22:59<01:58, 118.60s/it]

 - Saved Pickle file in 11.344s
Finalized sample>M&A, top-tech, 80, 4q, caliper_0.0500, 10matches with 6708721 rows.

Processing 01 Hybrid matches - M&A, top-tech, 90, 6q, caliper_0.1000, 10matches.pkl
 - Loaded sample in 1.249s
 - Combined with citations in 22.623s
 -> Total process_sample time: 24.688s
 - Merged with patents metadata in 2.076s

Processing samples: 100%|██████████| 120/120 [4:23:49<00:00, 131.91s/it]

 - Saved Pickle file in 21.916s
Finalized sample>M&A, top-tech, 90, 6q, caliper_0.1000, 10matches with 5477089 rows.

In [ ]:
patents.columns

Index(['ult_parent', 'acq_type', 'acq_date', 'acq_year', 'deal_id',
       'patent_id', 'acquired', 'assignee', 'grant_date', 'patent_type',
       'patent_date', 'patent_title', 'wipo_kind', 'num_claims', 'withdrawn',
       'filename', 'cpc_version_indicator_at_issue', 'cpc_section_at_issue',
       'cpc_class_at_issue', 'cpc_subclass_at_issue', 'cpc_group_at_issue',
       'cpc_type_at_issue', 'cpc_action_date_at_issue', 'merge_cpc_at_issue',
       'cpc_sequence_current', 'cpc_section_current', 'cpc_class_current',
       'cpc_subclass_current', 'cpc_group_current', 'cpc_type_current',
       'merge_cpc_current', 'assignee0_disamb', 'assignee1_disamb',
       'assignee2_disamb', 'has_multiple_assignees_disamb',
       'merge_assignee_disamb', 'assignee0_notdisamb', 'assignee1_notdisamb',
       'assignee2_notdisamb', 'merge_assignee_notdisamb', 'resold_date',
       'modnote', 'assignor', '_merge'],
      dtype='object')

In [ ]:
patents.head()

,ult_parent,acq_type,acq_date,acq_year,deal_id,acquired,assignee,grant_date,patent_type,patent_date,...,has_multiple_assignees_disamb,merge_assignee_disamb,assignee0_notdisamb,assignee1_notdisamb,assignee2_notdisamb,merge_assignee_notdisamb,resold_date,modnote,assignor,_merge
patent_id,,,,,,,,,,,,,,,,,,,,,
11100608,AMZ,M&A,1998-04-27,1998,1.0,0,"IMDb, Inc.",2021-08-24,utility,2021-08-24,...,0.0,Matched (3),"IMDb, Inc.",,,Matched (3),NaT,,,Missing updated (4)
5826258,AMZ,M&A,1998-08-04,1998,2.0,0,Junglee Corporation,1998-10-20,utility,1998-10-20,...,0.0,Matched (3),Junglee Corporation,,,Matched (3),NaT,,,Missing updated (4)
6199079,AMZ,M&A,1998-08-04,1998,2.0,0,Junglee Corporation,2001-03-06,utility,2001-03-06,...,0.0,Matched (3),Junglee Corporation,,,Matched (3),NaT,,,Missing updated (4)
6778980,AMZ,M&A,1999-02-23,1999,3.0,0,Drugstore.com,2004-08-17,utility,2004-08-17,...,0.0,Matched (3),Drugstore.com,,,Matched (3),NaT,,,Missing updated (4)
6947900,AMZ,M&A,1999-02-23,1999,3.0,0,Drugstore.com,2005-09-20,utility,2005-09-20,...,0.0,Matched (3),Drugstore.Com,,,Matched (3),NaT,,,Missing updated (4)

In [ ]:
patents.loc[['5159632']]

,ult_parent,acq_type,acq_date,acq_year,deal_id,acquired,assignee,grant_date,patent_type,patent_date,...,has_multiple_assignees_disamb,merge_assignee_disamb,assignee0_notdisamb,assignee1_notdisamb,assignee2_notdisamb,merge_assignee_notdisamb,resold_date,modnote,assignor,_merge
patent_id,,,,,,,,,,,,,,,,,,,,,
5159632,APPL,M&A,1997-02-06,1997,34.0,1,"NeXT Computer, Inc.",1992-10-27,utility,1992-10-27,...,0.0,Matched (3),"NeXT Computer, Inc.",,,Matched (3),NaT,,,Missing updated (4)

In [ ]:
patents['grant_date'] = pd.to_datetime(patents['grant_date'])
# Extract year, month, and quarter
patents['grant_year']  = patents['grant_date'].dt.year
patents['grant_month'] = patents['grant_date'].dt.month
patents['qtr']   = ((patents['grant_month'] - 1)//3 + 1).astype(str)
patents['grant_quarter'] = patents['grant_year'].astype(str) + 'Q' + patents['qtr']

In [ ]:
f = sample_patents.loc[['5159632']]
f['grant_quarter']

treated_id
5159632    1992Q4
Name: grant_quarter, dtype: object

In [ ]:
sample_patents = x.merge(patents, left_index=True, right_index=True, how="left")

merged = x.merge(citations, left_index=True, right_index=True, how="left")

merged.reset_index(inplace=True)
merged.rename(columns={"citation_count": "citation_treted", "citation_quarter"}, inplace=True)

merged.set_index("control_id")
comb = merged.merge(citations, left_index=True, right_index=True, how="left")